### ISSUE TITLE
Shield Refactor

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#116]

**Comment by Swampson** [comment]
Would this work the same way HP works when CON modifier increases?

**Comment by queryluke** [comment]
Correct. But I need to run it through my sheet that projects total hp per level. My fear is the 'double dipping' or INT. As an engineer, you'd get double the benefits (Shields and tech power attacks). Whereas Con doesn't have any connections to damaging powers.

**Comment by Swampson** [comment]
Here are my thoughts:

- Constitution is an ability that has no skills linked to it, so increasing your CON modifier will only ever impact skill checks, saving throws, and your HP.
- Increasing your INT modifier, on the other hand, also increases a number of linked skills, especially in this setting. I think that we could easily turn CON into a dump stat for a lot of classes if INT bonus gives you more shields.
- Having more Shield Points (SP) represents having a tougher shield, just as having more HP represents being a tougher character. I don't think it makes sense that shields would be directly affected by INT, because they are not an intrinsic part of a character. Shields are powered by a piece of worn equipment which can be upgraded. In short, I am in favor of keeping things as they are now, although thinking about it has caused me to come up with MORE questions:

- Should the rules specifically state that shields only work when a shield generator is equipped?
- Are shield generators built into armor or can they be worn without it? I don't know that this is ever directly addressed in source material, although I think it makes more sense that they are part of body armor. Maybe there could be a "light shield generator" that characters can discreetly wear when in street clothes that either provides lower shield points or that does not regenerate automatically but has to be recharged after an encounter.
- Should shields even be a part of the leveling process? In other words - should shield points simply be dictated by what model of shield generator you have equipped? This would require spending time creating a new type of item, but it also opens up the doors to more player choice and creativity (potentially). E.g, equipping shields that are not vulnerable to lighting damage, or shields that deal a small amount of damage to anyone who hits your character with a melee attack, etc.

**Comment by queryluke** [comment]
I'm in 100% agreement that shields should not be tied to int.

### Shield Refactor
The current concept is meant to replicate ME combat, where shields regen when you're not hit and constitute your 'primary' hp. Another benefit is that it compensates for the lack of healing spells (that put HP back on). Now there can be other spells that put SP back on.

But this presents a number of problems. First (as you pointed out), what happens if a player takes off their armor? I'd convinced myself that this wouldn't happen in a 'normal' game, but it should be an option (and I shouldn't dictate what's 'normal'). In 5e, you lose AC if you take off your armor, but in this system, you'd lose half your health pool?!?!? That doesn't make sense. 

Although I like the idea of a personal shield generator, I feel like that's just a band-aid for lazy game design.

The other issue with the current setup it that shields don't accurately reflect ME combat. In ME, you'd hide for a few seconds while your shields totally recharged, i.e. long pause -> fast recharge. But in the current rules it's short pause -> slow recharge. Plus, when you start getting to higher levels, the amount of shield regen each turn becomes inconsequential and another thing to keep track of.

This has me thinking that shields should be refactored (and thus I've changed the title of this issue).

### Proposal
* Shield points are 'temporary hit points' (which 5e has rules for)
  * I like this because it gives me equivalents in 5e to work off of for spells and tech powers
* The amount Shield points range for 5(common) - 50 (legendary)
  * This makes keeping track of shield points more manageable, but also doesn't make them required
* Shield points are acquired via armor mods or personal devices. 
  * I don't think spells or powers would give someone shield points, but they could recharge someone's shield mod or device
* You gain all of your Shield Points back on a short rest.
* If you take the Dodge or Hide action and take no damage until the start of your next turn, gain shield points equal to your shield's recharge speed (which would be all of the SP, unless the shield said otherwise, i.e. a shield might add +1 AC but only offer 1/4 recharge speed).
  * I like this because it forces a player to choose to regain shields, much like they might choose to cast a healing spell. It also gives a pretty nice benefit to Dodge (which I honestly didn't know existed until I was reviewing combat actions)

**Comment by Swampson** [comment]
I think these are great ideas. The only thing I think I'd suggest changing is "You gain all of your Shield Points back on a short rest." Since you can recharge shields fully in one action (with "Dodge" or "Hide"), I think you could reasonably say "You gain all of your shield points back at the end of an encounter".

**Comment by queryluke** [comment]
Good point. I forgot there are GM's that don't give their players short rests between combat ...cough* cough*...totally not me and that first 4 hour intro combat session we had.

**Comment by queryluke** [comment]
Broke this out into it's own milestone and separate issues:
#125 #123 #124 #122 #112 
 leaving this here as a reminder to add the rule change.

**Comment by Swampson** [comment]
Ha! I think the onus is actually usually on the players to declare they want to take a short rest.
