### ISSUE TITLE
Spell change: Lift

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#119]
Seemed under powered in play testing. Remove HP comparison to other save or increase dice? An additional option to alter this and Singularities mechanic, perhaps swap spell levels as well.

**Comment by queryluke** [comment]
Note: this will effect the adept disruptor subclass

**Comment by Swampson** [comment]
I think the issue with Lift is that it's primary value in combat is as a primer. I don't know that the prime/detonate combo is as front-and-center as it needs to be in order to be a meaningful component of gameplay. 
I recall that when I played an Adept (in a much earlier version of the game, to be sure) I felt like there wasn't much opportunity for me to either set-up combos for my squad-mates or for them to set-up combos for me. And the one or two times I was able to pull off a combo by myself I felt the additional damage was inconsequential compared to the effort required in getting the combo off.
At this point I have not really looked to closely into all the options for priming and detonating, so I'm not sure if my earlier gameplay impressions are still valid.
What I would say is that Lift itself might not require any changes IF we can bring the combo gameplay a bit more forward in player's minds.
Other things to consider with Lift itself:
- it could still serve as a valuable utility spell out of combat (I am thinking mage hand here)
- the caste or their allies might have advantage on intimidation rolls agains _lifted_ characters
- in the source material (i.e. the Mass Effect games) a _lifted_ character can't do ANYTHING. They just float around with their butts hanging out, so maybe a Lifted character cannot attack (even with disadvantage) and automatically saves all STR and DEX saving throws. That would certainly put them in a more precarious position and make this a more valuable (maybe even OP?) control spell.

**Comment by queryluke** [comment]
So the different between lift and singularity was:
* lift has no cap on size, just the die rolled. So you could theoretically lift very large creatures, but base level is 5d8 which is only 45 hp, that's a CR 1/2 at best.
* singularity is multiple targets but only affects medium creatures.

So I'm thinking lift will be a spell attack roll, lift the target, concentration to maintain, only effects medium targets. One of the advanced versions affects large targets.

**Comment by SrShdw** [comment]
I think the Lift spell itself is well designed. It seems like it's based off the Sleep spell but is single target, and I like that since it has the power to be just as debilitating as sleep. Since it is only single target, you might want to increase the base number of dice for the level 1 power if you're concerned about it being relevant. You could also increase the number of dice you get per biotic level over level 1 since there are only 5 levels of biotic power (and only Adepts even get to use the 5th level slots). It might also be a good idea to make it Xd8+Y where Y is your biotic caster level so that it can scale a bit more

**Comment by queryluke** [comment]
@SrShdw, yeah this is a re-skinned, single target sleep. I like the fact that, currently, there is no size limitation to this spell (I imaging a high-lvl biotic lifting a tank, which would be unaffected by singularity). 

But HP scales with CR, so this power is limited by the creature's CR, whereas something like singularity is limited by size. Take the example of a Collector Trooper (55 hp). Even if we boosted to 7d8, it would take a max roll to lift it. However, singularity could lift multiple Troopers if they failed their Dex sav. Sing is a 3rd level spell, but my the fact that it can lift multiple targets is the main reason for it being of a higher level.

I think we need to find a sweet spot, maybe it's half the creature's HP? There would still be discrepancies, like a Cerberus Guardian (130 HP). Or may this calls for a singularity nerf, instead?

Another possibility is to re-skin sleep as singularity, keeping the exact same mechanic, but lifted instead of incapacitated. We could drop singularities level if need be and boost the dice amount. Then make lift a spell attack.
