### ISSUE TITLE
New Skills for Setting

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#158]
As I am working on the character backgrounds, I believe there are some skills that need to be added to allow for playing a full ME 5e campaign. This is my initial list for review and discussion:

- **Science[Intelligence]** (Basically replaces _Arcana_). I really don't like the flavor of distilling everything from astrophysics to psychology down to the eye-rollingly banal "Science!" trope, but I also think that one of the nice things about 5e is that it doesn't have an over-long list of skills. To mitigate this, maybe a scientist background would provide not only proficiency with this skill, but also advantage on rolls made when applying the scientist's specific field of study (e.g. "astronomy", "xenobiology", "geology", or "economics"). We could hand-wave the umbrella use of "science" as a catch-all by pointing-out the ubiquity of hand-helps terminals and VIs. Incidentally, I think this could encapsulate the traditional "Animal Handling" into this skill IF the character has a specialized study of biology/zoology.
- **Driving [Dexterity]**. I think for the purposes of the game this would involve the operation of any ground-based vehicle, including hover-craft. Basically, any vehicle that would be primarily moving in two dimensions along the ground or surface of the water. 
- **Piloting [Dex or Int]**. This one gets a bit tricky because, there are two types of piloting we could be dealing with. Dex-based piloting could include things like starfighters or transport (the ubiquitous "combat cockroach"), especially if they are in-atmosphere. However, the operation of anything like the type of ship you'd expect a party of PCs to operate (a frigate like the _Normandy_) would probably use Int. So should this be two separate skills? If so, what do we do about Navigation (see below).
- **Navigation [Int]**. This would specifically be interstellar navigation. I think any type of on-planet nav could reasonably covered by the existing 'Survival' skill, at least for now
- **Gunnery [Dex or Int]** - Operation of Ship-based Weapons Systems. As I'm typing this I'm really thinking it should be more Int-based than Dex-based.

**Comment by queryluke** [comment]
My only hesitation is adding too many new skills. I don't know D&D's reasons for going with 18, but I feel they must have done some theory crafting around how many is too many and how many is too few. So I think it might be worth going for a one-in, one-out rule.

My other concern is that a lot of new 'tech-based' skills will naturally lean towards intelligence, which adds a premium for intelligence over the other attributes.

As it stands now, the three new ones are Hacking, Engineering, and Piloting.

Perhaps Engineering could shift to wisdom based, since repair does has a level of wisdom surrounding it (i.e. assessing the problem, trouble-shooting solutions). Take Kaylee in Firefly who is a great example of high-wisdom. This would also mean Engineering could take the place of Animal Handling, since you're handling ships and crafts but not animals.

Piloting is already there and is Int based, replacing Religion. I feel being Int based, it could over Navigation as well.

I wonder if Driving and Gunnery can be covered by Sleight of Hand, since all involved eye-hand coordination and a 'feel' for the activity. Or Gunnery (to make it Int based) might be covered by Hacking. Or Hacking can get the all-generic term "Computers" and cover both hacking and gunning (or working with any computer based system).

Leaving Science, which might be a good replacement for Nature, being Int based and possibly sub-skilled as you mentioned.

**Comment by Swampson** [comment]
After thinking about it overnight and reading your reply, I think the thing that really needs to happen is to map some or all of the 18 skills to ship-side counterparts (see #159). I definitely agree about not expanding the skill list if we can help it. I’ll post a revised proposal soon.

**Comment by Swampson** [comment]
After further consideration, I think the only changes that needs to happen are:

- "Nature" becomes "Science" (still based on Int)
- We **may** want to change "Piloting" to something like "Driving" or "Vehicle Handling" and have it apply to small craft, especially ones designed for in-atmo transport. If we want to keep a very strict one-in, one-out policy for skills from 5e, this skill replaces _Animal Handling_ and is therefor based on Wisdom. However, that doesn't make a lot of sense to me. I'd suggest we base this on Dex or Int. Another option is to use the [_Variant: Skills with Different Abilities_ rule](https://roll20.net/compendium/dnd5e/Ability%20Scores#toc_7), but I think that could potentially make things very confusing. 

Just for reference, here are the skills that we've replaced from core 5e rules:

5e Skill | ME Skill | Attribute
-- | -- | --
Arcana | Engineering | Intelligence
Religion | Hacking/Computers | Intelligence
Nature | Science | Intelligence
Animal Handling | Vehicle Handling | Wisdom / Int / Dex

**Comment by queryluke** [comment]
As it stands now, I'm not following the 1-in-1-out rule. Engineering, Hacking, and Piloting are all intelligence (one less wisdom).

I think Vehicle handling makes sense to be baseline Dex. But we can put a note in there like, "You're GM can also ask for a Vehicle Handling (Wisdom) roll to see if you can pilot new vehicles which you've never driven before". I think this would be wisdom over int, because it refers to the ability to transfer skills that rely on feel and general control layout.

**Comment by Swampson** [comment]
I wish there was a "chef kiss" reaction in Github so that I could apply it to @queryluke 's last reply.

**Comment by queryluke** [comment]
I'll make this change in 0.5.1 or 0.6.0, but you can structure the backgrounds work around this for now.
