### ISSUE TITLE
Race armor restrictions

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#181]
Are the racial armor restrictions worth it? Would it be better to shift them back to classes?

* adept & infiltrator: light
* engineer & vanguard: light, medium
* soldier & sentinel: all

If so, I'd also like to remove the racial cost of armor customization. It's interesting, but does it serve much of a purpose besides making armor cost more.

**Comment by Swampson** [comment]
Similar to your thoughts on #121, I would suggest revising the rules to bring them more in line with the 5e core ruleset. In other words, having armor proficiency be based on class instead of race. Further, I would suggest removing the rule which states a character **cannot** wear armor they are not proficient with, and letting the standard 5e rule apply:

> Anyone can put on a suit of armor or strap a Shield to an arm. Only those proficient in the armor’s use know how to wear it effectively, however. Your class gives you proficiency with certain types of armor. If you wear armor that you lack proficiency with, you have disadvantage on any ability check, saving throw, or Attack roll that involves Strength or Dexterity, and you can’t cast Spells.

This allows for more player creativity and risk-taking (e.g. an adept electing to temporarily wear heavy armor as part of a disguise, etc).

With regards to the racial cost of customization, I think this falls into the category of a setting guideline as opposed to an actual rule. The cost of armor could vary quite a bit depending on where the PCs are and who is making the armor. For example, a Volus shopping for custom armor on Palaven (the Turian homeworld) is likely going to have to pay a premium for custom armor (and if she were instead on a Turian _colony_, it may make sense that no custom armor can be made and she'd have to pay a premium for ready-made armor.

Even the above may be too much of a guideline, because it assumes that armor is made in a way similar to how we manufacture things in the present-day real world. Mass Effect already has the concept of "minifacturing" baked-in to the setting, so it could be argued that anyone could have a set of armor made provided they have schematics that can be loaded-into a manufacturing machine of some type. But then _this_ in turn opens the door for a lot of extra complexity for having armor schematics of various kinds ...

I think what would make the most sense is to leave the relative availability and cost of armor up the GM's (Galaxy Master tm tm tm) discretion. We can remove the 5,000 credit customization fee and add some kind of footnote for GM's that they may want to give some consideration as to how they want to handle this.
