### ISSUE TITLE
Nav Menu Intermittently Unavailable in PHB

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#183]
This is a very elusive and minor bug as I'm not able to re-create it consistently, but I thought it would be worth opening an issue just in case it's something someone else has seen.

Occasionally, when loading the PHB main page, the nav menu does not appear, either as a hamburger menu icon or in its default on-screen layout. At first I thought it might be a discrepancy with the responsive break points (a small range of screen widths where both elements are set to display:none), but this is not the case.

When this bug appears I'm able to get the menu to "pop in" by resizing the browser or refreshing the page. It's appeared in Chrome for both macOS and Windows 10.

**Comment by queryluke** [comment]
Ah! thanks for pointing this out. I've noticed it myself but wasn't sure if it was due to the fact that I often have conflicting cached versions of the compiled javascript butting heads on my machine. Now that I know it's valid, I can try to figure out what's going on. I have a suspicion.

**Comment by queryluke** [comment]
Note to self:
### To recreate
Open phb. Resize to where the menu hides and hamburger shows up. Close Tab. Open tab again and navigate back to phb.

### Cause
I think this is due to the persistent storage plugin. Whether to hide/show menu is stored on the client's browser. When breakpoint hits for small browser, menu is set to false. If the person returns, menu remains set to false.

### Solution
I think this was fixed this [this commit](https://github.com/queryluke/masseffect-5e/commit/56ddef3a90e5253f9bcad1d35312c9dbc08083a6), because it limited the persistent storage to only specific variables, excluding the site menu, but need to test.
