### ISSUE TITLE
Does melee Pierce Shields

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#189]
Overall melee weapons seem on the weaker side, and this would offer an incentive to go melee when everyone is shooting at you from a mile away.  Also I think it lines up with lore

**Comment by queryluke** [comment]
Hmmm. That's a good point. According to the [codex entry](http://masseffect.wikia.com/wiki/Codex/Weapons,_Armor_and_Equipment#Kinetic_Barriers_.28.22Shields.22.29)

>Kinetic barriers are repulsive mass effect fields projected from tiny emitters. These shields safely deflect small objects traveling at rapid velocities. This affords protection from bullets and other dangerous projectiles, but still allows the user to sit down without knocking away their chair.

>The shielding afforded by kinetic barriers does not protect against extremes of temperature, toxins, or radiation.

From this, it would also make since that shields wouldn't block additional damage types like radiant, fire, cold, etc.

On the one hand, I prefer leaning into the lore. But this adds a considerable level of complexity to combat. 'rapid velocities' could simply mean 'fired from a weapon', but it gets grey when dealing with a biotic ability like catapult.

Instead of a global rule, I think I would need to expand the list of spells and include weapons that bypass shields, an exception already found on necrotic powers like warp.

I'm not sure this completely fixes melee weapons being on the weaker side, but I kind of like that about the system: akin to bringing a knife to a gun fight. For the majority of characters, the melee strikes are a back-up to their normal abilities if a creature closes in on them. For others that are trying to go down the melee route, I've tried to accommodate with class features. Ghost infiltrators get increased sneak attack damage die. Sentinels, Soldiers, and Vanguards can choose the brawler fighting style, which makes them very unlikely to miss with an attack. Weapon Master Soldiers and Shock trooper Vanguards get Weapon of Choice and Biotic Slash, respectively. Finally, anyone running melee could benefit from two-weapon fighting, making additional attacks on each turn. To be honest, I'll need to do some additional play testing to make sure these abilities scale appropriately against ranged weapons.
