### ISSUE TITLE
Tech class progression

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#190]
I've been looking over the tech classes, and while the system itself seems really customizable and fun, on first glance I feel like infiltrators and sentinels simply don't get enough opportunity to learn abilities.  Sentinel get 6(?) And infiltrators have to slit with combat abilities.  Ironically I only see this as a potential issue because as a player I would want more opportunities to get abilities and improve them since there is such a large pool.  I think adding just a few more opportunities to learn tech abilities,. Either in level progression or some kind of spell scroll (1 time abilities) or being able to learn tech separate of levels might be a good addition.  That being said, biotics look really well balanced and spread among level progression.

**Comment by queryluke** [comment]
@TheMarmotKing Thanks for pointing this out.

When I refactored the Infiltrators, it looks like I definitely didn't allot enough tech powers. Here is my overall count:

* Adept: 11 biotic
* Engineer: 10 tech
* Infiltrators: 6 tech
* Sentinels: (9) 4 tech, 5 biotic
* Soldiers: 5 combat (10 w/ Havoc)
* Vanguard: 9 biotic

When I look at these numbers, I notice a few things:

1. Yes, Infiltrators are way too low comparatively
2. Adept and Engineers as the 'pure caster' classes should probably have more options.

I think the sweet spot for the casters should be 12-14, giving the player 7-14 spells, depending on advancement options.

Non-casters should land between 8-10, because they get other class features along the way. The primary exception being Soldiers, since they are so weapon heavy.

I guess all of that was to say that

1. Yes, Infiltrators need at least 2 more tech power opportunities
2. Sentinels, should at least get 1 more tech power. Replacing Sentinel Mastery seems like a good opportunity
2. Engineers and Adepts ~2 more.

**Comment by TheMarmotKing** [comment]
Those seem like fair changes. Just enough to offer a bit more opportunities to use the different skills.  Sentinel poor sentinel has 1 tech point and tech armor at level 1, they really wait till late to scale.  But I think when I run a campaign with this mod I may offer the ability to purchase 1 time tech abilities (like a 2 TP incinerate for 2000 creds).  Might also be interesting to offer a (expensive) redistribution of skill points.  A very expensive service, but matching up with in game mechanics.  Overall though I think the increase makes the abilities pretty balanced for each class.
