### ISSUE TITLE
Roll 20 Character Sheet

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#194]

**Comment by EnricoDandolo1** [comment]
Hey! Planning to run ME 5e in an upcoming campaign and I've prepared a pretty rough adaptation of the 5e OGL character sheet for it. This is pretty much my first time working with HTML/CSS so it's still fairly rough around the edges. It's pretty functional so far, but I'll list a couple things I'd want to change in the medium term.

1. Translation and display for shield points on NPC sheets needs to be fixe
2. Find a better way to implement tech powers and differentiate tech, combat and biotics powers (colour-coding?)
3. Add trackers for thermal clips, medigel, grenade and omnigel.
4. Some minor fixes (e.g. proficiency bonus doesn't update automatically when changing character level)
5. Automate spell slots for biotic classes -- couldn't figure out a way to do this as it seemed to me sentinels, vanguard and biotics all follow different spell slot progression tables, unlike the full, half and third casters in vanilla.
6. Clean up the first page a bit. Auto-calculate AC from equipped armour pieces using drop-down menus, and re-enable encumbrance system (I disabled it since most of the items added by the conversion don't seem to have weights attached so far, especially stuff like adventuring gear and background equipment. Also, a fair amount of property would be digital, like deeds or special omni-tool programs).

It's still pretty rough-around the edges, but me and two of my players have been able to write up characters with it quite easily. I use roll20's Ammo Tracking feature for weapon heat; since the sheet would presumably require a subscription to use in the first place, that might as well be assumed to be available.

[charsheet css.txt](https://github.com/queryluke/masseffect-5e/files/2282729/charsheet.css.txt)
[charsheet html.txt](https://github.com/queryluke/masseffect-5e/files/2282730/charsheet.html.txt)
[charshee translations.txt](https://github.com/queryluke/masseffect-5e/files/2282724/charshee.translations.txt)

**Comment by bpmcpherson** [comment]
You shouldn't need a subscription to use the sheet, so long as it is part of the open-source repository. Case-in-point, I've used the Naruto d20 character which was made by a friend of mine in my game and I'm not a Roll20 subscriber.

**Comment by queryluke** [comment]
@EnricoDandolo1 This is really exciting!

**Comment by queryluke** [comment]
Included info and links in #382.

Perhaps we'll com back to this later but the work done so far is excellent.
