### ISSUE TITLE
Perception starting skill

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#199]
From feedback form

> Only the Adept and the Sentinel classes get the Perception as a class skill.

**Comment by Swampson** [comment]
This may be something to be addressed via the backgrounds. Here's my reasoning:

- The OGL version of 5e has 12 classes, whereas ME5e only has 6. This is approximately 50% fewer classes (rounding down).
- The ME5e classes are all heavily-geared toward combat, per the source material
- It follows that the ME5e backgrounds should offer even more robust opportunity for character development.

To that end, I was considering writing Backgrounds that allow for three skill proficiencies instead of two. Or perhaps three skill proficiencies if you give up something else (in lieu of a tool proficiency perhaps)?

**Comment by queryluke** [comment]
aha! excellent point. I'd forgotten that backgrounds provide skill options. Yes, once backgrounds are introduced this will not be an issue.
