### ISSUE TITLE
Variant Respec rule

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#204]
A variant rule that would allow players to "respec", I.e. choose a different subclass and powers.

**Comment by Nmmoriarty** [comment]
While I like the idea since it is in the Bioware game, I'm not sure this really applies to the PnP format we're using here.  What is respecced?  Skills?  Skills you gain from your background?  Weapon Proficiency?  Powers?  Subclasses?  Classes?  There are a lot of consequences to think of, and I'm not sure it would be worth the effort.  I think this should be handled as a GM-Player thing, not really covered by the rules, because I assume most players are going to put thought into what choices they make for the character, and if they make bad ones because they just didn't know, I feel it would be GM fiat thing to let them mulligan.

**Comment by queryluke** [comment]
That's honestly enough to sell me. As you say, If GMs and players want to figure out a respec rule I think it's up to them to work out the details. I have often talked my GM in to switching 5th edition subclasses based on some extraordinary circumstance, but it's not listed anywhere as an explicit variant.
