### ISSUE TITLE
Krogans As Engineers As Featured in Andromeda

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#212]
Along the many new additions to the franchise that Andromeda brought, one thing is that the multiplayer freatures Krogan as Engineers. 

http://masseffect.wikia.com/wiki/Krogan_Engineer

**Comment by queryluke** [comment]
Great minds...I actually had krogans as engineers in an earlier version, I think up to 0.4.0. I removed it because of a long, offline discussion that wasn't very 'logical'. Knowing that others see legitimacy in this is plenty reason to include it. I've scanned the lore and can't find any reason why Krogans wouldn't have a small portion of the population that would be able to fit the Engineer mold.
