### ISSUE TITLE
Additional Backgrounds

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#223]
Just putting a link to my Google Sheets page that I'm using to develop additional backgrounds. It will be updated as more are developed. 

## Current Backgrounds:

- **Criminal**
- **Doctor**

## **Based on Andromeda Backgrounds**
- **Security** - During your Alliance military service, you focused on learning everything you could about weapons and tactics.
- **Biotic** - You were effectively 'designated biotic' during your Alliance military tenure, assisting your cohorts with your ability to control mass effect fields.
- **Technician** - As a technician in the Systems Alliance military, you learned to operate drones and hack enemy systems.
- **Leader** - You were a team player and a natural leader in the Alliance military, working closely with your cohorts for their safety and the safety of others.
- **Scrapper** - When a fight broke out, you were always the first soldier in the thick of it - mostly according to Alliance military protocol and occasionally not.
- **Operative** - In the Alliance Military, you studied covert operations and the tech used by special forces - knowledge you rarely found a use for until the Andromeda Initiative.

https://docs.google.com/spreadsheets/d/1OFRndihY2KsEnmEHCVzZue8QU4LKU6nQ387f17vNwhE/edit?usp=sharing

**Comment by queryluke** [comment]
@Swampson has also been working on some backgrounds. I'll let the two of you get in touch and hammer out some details.

FYI - I removed them from the new site because there were only 4 and they referenced things that didn't exist (some kits). I threw them in in version 0.3.0 and never really even looked at them because they were contributed by someone else. 

However, if you group does need the original list, here is the doc I was using:
https://docs.google.com/spreadsheets/d/1UYrhjspTwj6_lzndHJcu4pMssu7POagKS5HxbYtZ03Y/edit?usp=sharing
