### ISSUE TITLE
Weapon Mod Feedback

### ISSUE THREAD

**Issue by Nmmoriarty** [queryluke/masseffect-5e#238]
I figured we should get this started.  My first suggestion is about how Core mods are handled.  Firstly, all these really deal with ammo let's call them ammo mods.  

Secondly, do we want to include something to make it so you can have different ammo types installed, or make ammo "powers" a different system altogether?  I guess the question here really lies in how powerful/important having the right ammo type is.  While this certainly was the case in the Bioware games, they seem of diminished importance in this adaptation.  I don't think this is a bad thing; we want to make a game which is balanced and fun, not just mindlessly port the Bioware game into a pen and paper setting (Looking at you, MEd20).

Thirdly, how piercing ammo works is a little wonky -- values for how "thick" cover is was never addressed in 5th ed, just how much you're getting.  Ostensibly, how good your cover is depends also on what material it is made out of (A paper screen door is going to provide no substantive cover bonus, logically), so I think we could simply it and just have piercing Ammo drop cover bonuses a level, with half cover dropping off entirely.  This might be a little powerful, so I'm looking for suggestions on this one.

Lastly, and kinda related to the first point, this leaves shredder ammo (and piercing depending on how we want to go) being the only one with tiers of power.  I think we should align it so either piercing and shredding have no tiers, or give other ammo type tiers.  Depends on how complicated we want to get.

Another thing I was looking at was if we should have another limit on mods outside of just one per slot, but I haven't done the math on those yet to see if you can make some truly broken stuff with the mod system as it is.

**Comment by Nmmoriarty** [comment]
After reviewing the Weapon Mod system, I figure the best way to test this is to make the most absurd damage combination I possibly can.

- The highest damage non-heavy weapon is the old standby, the Black Widow, coming in at 4d10 (average 22 damage), and Heat 1.
- Be a Solider, level 20, Dex 20, take the Sniper subclass and Sniper Fighting Style.  This provides +11 to hit (with advantage under certain circumstances), +5 to damage (an additional +12 if you are using the Deadly Aim subclass ability and an additional +6 if no enemies are within 10m), an average 2.5 extra crit range with Adrenaline Rush, and five attacks (one base, three from extra attack, one more from Snapshot, though the wording on Snapshot is unclear).
- Take the Sharpshooter feat.  You can trade 5 attack bonus for 10 damage.  This goes well with stealth for the advantage on attack rolls to make up for the attack bonus penalty, so let's assume you also picked up Stealth as a skill from something, probably the Skilled feat.  While we're at it, let's pick up Sleight of Hand too and get the bonus on Rapid Reload.
- Pick up the Tactical Scan power for 19-20 crit threat range.  Since Turbocharge is going to get a nerf, I'm not 100% sure on how this shakes out, but that could provide an extra 2d10 damage on the Black Widow, and negates the need to reload.
- Slap on Concentration Mod III for an average crit threat range of 17, High Caliber Barrel for +3 attack and damage, Magazine Upgrade V for +10 heat, and an ammo mod of your choice, since none of them really provide bonus that isn't situational.

Let's blow everything we've got on this.  Use Tactical scan, be hiding from the target, use Deadly Aim, use Sharpshooter, use Turbocharge.  

Our grand total is a Black Widow that rolls five attacks +9 to hit with advantage, hits with 6d10+33 damage (average of 66 damage), has an average crit range of 14-20, a heat of 11, and +11 to Rapid Reload checks.  On average, one of those five attacks hits is a crit (30% chance to crit), giving us 12d10+66, average 132 damage on a crit.  I'm sure you could do even more average damage with Infiltrator (Operative), but I haven't math hammered that yet.

**Comment by Duneday** [comment]
Yeah Infiltrator is by far the most damaging class by a long shot. I just used it in a comparison to a salvo specialist actually. Just because you mentioned it though, the extra attack from Snapshot is only for the first attack action you take in an encounter. Therefore you only get 5 attacks the first round after that it would be down to 4. Just a clarification.

**Comment by Nmmoriarty** [comment]
The difference between the Soldier and the Infiltrator here, @Duneday is that the Infiltrator gets one attack, needs the target to fail a Con save, and has a 20% crit chance.  The Soldier gets five attacks (and due to the Magazine Upgrade can take advantage of all of them without needing to reload... for two turns of shooting), 35% crit chance.  The Soldier's damage per round and average damage is greater than the Infiltrator's.

Both are still an absurd amount of damage as it stands, and will melt even 20th level enemies in a round.  Hell, Soldier could melt five of them, making combat a paltry affair.

**Comment by Duneday** [comment]
First thing: I was pointing out the rule for snapshot, which would only trigger for your first round of attacks. Meaning that Soldier would get 5 attacks for the first round and then 4 after that. Second: My point on the infiltrator admittedly was based on my build which involves multiclassing, I should have clarified that point, but it wasnt what I had posted as a main idea so I didnt think too much about it.

**Comment by Nmmoriarty** [comment]
I think that Magazine Upgrade is a bit too abuse-able with it just adding a flat heat value to a weapon.  I think there should be two ranks of it, one giving 50% more heat (round down) and one that gives 100% more heat.

**Comment by queryluke** [comment]
### Proposed changes:
* Rename "core" type to "ammo"
* Cranial Trauma Mod: Limit to one level (1 additional damage die on critical hit)
* Power magnifier: Limit to one level (currently lvl 3 has potential to add +9 with some subclasses). 
* Concentration Mod: Limit to one level (19-20 crit) 
* Piercing Mod: Rename piercing ammo. Has same toggleable as other ammo mods. Ignores 2 AC if target is behind cover.
* Shredder mod: Rename shredder ammo. Has same toggleable as other ammo mods. Changed damage type to slashing. An unprotected, organic creature that is hit by this weapon looses 2d4 hit points at the start of it's next turn due to bleeding.
* Quick release magazine: Limit to 3 levels (in line with others)
* Magazine upgrade: Limit to 1 level. Weapon gains a bonus to heat equal to 1/2 it's base heat score. (useless for 1 heat weapons)
* Extended Magazine: New. Weapon gains a bonus to heat equal to twice it's base heat score (limited for 1 heat weapons)
* Heat sink: remove...why add more rolling?

The only downside is that now there are only 2 magazine mods. Not really sure what to do about this. I guess we could combine the magazine and ammo mods. You get the choice of new ammo, more shots, possibility of faster reload.

**Comment by bpmcpherson** [comment]
Magazines are simply the most simply component to upgrade, so simply having different ammo types and a larger magazine is fine.

**Comment by queryluke** [comment]
### Armor mods overlapping with weapon mods
I looked over the current armor mods, and they are pretty diverse. I think I can just remove or change any of the armor mods that provided bonuses to ranged weapon attack or damage rolls.
* VI Amiming
* Weapon Stabilizers
* Focus Modulator

I'll put a note in the rules about creating custom armor mods that ranged weapon attack and damage bonuses should remain on weapon mods.

### Armor mods overlapping with other armor mods
First, make a note that a mod cannot be applied twice to a piece of armor. (I.e., can't apply 2 +2 AC mods into a chest piece)
Here are all the places that the current list of armor mods can be stacked

* Weapon slots (no issue)
* Increased HP, I don't like this mod anyway. I think swapping to the "ignore critical" is a better fit. (note to self to change on armor sets)
* +Melee attack and damage rolls. Change the legs to a +1, giving a max +3 when stacked.
* Resistances (could be taken advantage of but they are very expensive, don't think it currently warrants a change)
* grenade capacity (no issue)
* shield points. I want to change +SP to chest only, since this is where the shield generator lives anyway.
* shield regen (no issue, can only stack to 15 currently, but has a ceiling of the character's sp)
* tech regen die type (no issue, max d12 and only happens on a short rest)
* thermal clip capacity (no issue)
* "jump start shield regen", instead of taking hide or dodge action. (no issue. Only 2, even with 4, I'd be ok because they're taking up slots that would increase shields or regen).
* Autogel, I guess this would let you use 2 charges of medigel...but I don't have a problem with that either.

**Comment by Nmmoriarty** [comment]
Alternatively, if we want to limit on how many mods you can have on a weapon.  And I agree with @bpmcpherson, if we had a magazine upgrade that essentially let you switch to another ammo mod, that might be interesting -- but that all depends on how much you wanted ammo type to be a tactical choice.
