### ISSUE TITLE
Rapid Reload Feedback

### ISSUE THREAD

**Issue by Nmmoriarty** [queryluke/masseffect-5e#239]
There are a few things that are misaligned about how Rapid Reload is worded, so here is my suggestion to reword it.

> If you are only wielding one weapon, you may attempt a Rapid Reload action as a Reaction during your attack action.  Make a DC 15 Dexterity (Sleight of Hand) check. On a success, you reload your currently equipped weapon and may continue your attack action.  On a failure, the weapon is not reloaded, but you may reload as an action on your turn, and you may not continue your attack action.  If the d20 roll for this action is a 1, you fumble and the thermal clip drops from your hands; your weapon is not reloaded, you may not continue your attack action, and you must recover the clip or retrieve a different one to reload.

I guess the question is what is the action cost of grabbing a thermal clip?  RAW, there isn't much point to a botched Rapid Reload.  Dropped my thermal clip?  No matter, I'll just grab another one of my infinite amount of these unless I'm playing with the rule where I have to keep track of them.  I think there should be some risk other than just having to reload like normal, otherwise everyone attempts a rapid reload at no real penalty other than having to do it still.  I assume for the regular reload, drawing a clip from your bandoleer is included, but should it have an action cost otherwise as a bonus action (like drawing an item is in 5th)?

**Comment by queryluke** [comment]
My only intent for Rapid Reload is to give players a chance to reload a weapon and take their action. I used to have it as a bonus action, and switched it to a reaction. But perhaps that was the mistake. If we switched back to bonus action, most people would probably still attempt it, unless they had a lot of other abilities which require bonus actions. Then RR might seem like more of a cost. 

As it stands now, I see your point. Everyone would attempt a rapid reload, and if they failed, then they lose that single round of combat (when they reload the clip). But the only cost is a 5% chance of losing 2 rounds of combat. And/or losing their reaction.

RE: your proposal
My understanding of reactions is that they must happen in response to something. I've always read, "As a reaction to X, you may Y" Perhaps a minor rewording "As a Reaction to taking the Attack action, you may..."

The other thing I'm a bit confused by is:
1. Player states: "I'm taking the attack action" (they have no heat in their weapon)
2: "Now I'm taking the Rapid Reload action"
3: Fails Saving Throw
4: They can't attack and can't do anything else because they've already declared the Attack action.
5: Next turn they can try to RR again, or reload as normal.
So on a failed save, they lose their action and they can't reload their weapon until their next turn (which takes the entire action). So they've really lost 2 turns, which was my intent for the critical failure. 

Am I misinterpreting?

**Comment by Nmmoriarty** [comment]
There isn't really an elegant way to accomplish reloading as a non-attack action during your attack action.  I was trying to make the action be ammo-efficient, keeping in mind the limited ammo variant rule and not wasting specialized thermal clips (when they were a thing, anyway).  Ostensibly, you want to reload when your count hits zero, and a reaction would, in theory, allow you to reload mid-attack action and keep going if you still had attack rolls left in the action.  Alternatively, it could be reworded with "If the heat count in your weapon is zero, you may attempt..." to be more exact.

I also wanted to make sure there was a downside to missing a rapid reload, in some variety.  I toyed with the idea of missing the roll forcing you to spend an action to reload (so you don't try to reload as a bonus at the end of your turn, then if you mess up you just try as a bonus again your next turn, effectively not giving you a consequence for failure outside of total failure), but it seemed difficult to balance against the consequences of a critical fumble.

Effectively, there are three outcomes of a Rapid Reload:

1. Success.  You reload faster than normal, a bonus or reaction.
2. Failure.  You reload slower than you would have if you had just done it normally, otherwise everyone will always try to Rapid Reload if there isn't a consequence for failure.  This means you burned your reaction/bonus action and the action needed to reload.  Otherwise, as a reaction that you moved it to, there is no consequence to rapid reloading if it just costs the rest of their attack action to reload other than wasting what is left in the clip. which isn't a consequence depending on the rules you are using.
3. Critical Failure: Very punishing, as an extra "don't try this unless you're sure it is worth the risk." This could be the losing the bonus/reaction and two actions.

I guess it boils down to what is more useful in this system, the Bonus or Reaction actions?  Which would would work better in terms of what you want to accomplish?

**Comment by queryluke** [comment]
>You reload slower than you would have if you had just done it normally, otherwise everyone will always try to Rapid Reload if there isn't a consequence for failure.

Personally, I don't mind this but, game-wise, we're adding needless rolls. So I totally get your point. And I think I'm starting to parse your proposal correctly:

There are three scenarios that need to be covered are:
1. Player begins turn with 0 heat in weapon
2. Player ends turn with 0 heat in weapon
3. Player with Extra Attack has 0 heat in the middle of their multiple attacks.

>If you are only wielding one weapon, you may attempt a Rapid Reload action as a Reaction during your attack action.
1. Player must declare attack action to attempt rapid reload
2. Not available (turn has ended). Would be available as 1 at start of next turn.
3. Player in midst of attack action (thus, RR is applicable)

>On a success, you reload your currently equipped weapon and may continue your attack action.
Pretty straight forward.

>On a failure, the weapon is not reloaded, but you may reload as an action on your turn, and you may not continue your attack action.
1. Player cannot attack. But can take the Reload action (or a different action)
2. N/A
3. Player's attack ends (would need to take the attack action a the start of next turn)

In case 1, the current rule still applies, the player could take the reload action (or they may decide to cast a spell or other). The main difference is that the current rule requires the player to reload.

In case 2, it's almost required, otherwise the player can't continue their attacks. 

> If the d20 roll for this action is a 1, you fumble and the thermal clip drops from your hands; your weapon is not reloaded, you may not continue your attack action, and you must recover the clip or retrieve a different one to reload.
Straightforward as well.

As I broke this down, I'm starting to see the main problem is that the current rule doesn't have language for "inter-attack-action" reloading. But it would also be beneficial to dissuade cases 1 & 3 from attempting a RR unless they're sure they can accomplish it.

More noodling required!

**Comment by queryluke** [comment]
Had a meeting with @Swampson and we think Rapid Reload is just a bit too cumbersome to support. Instead, we're going to change the quick release magazine to simply state: "You can reload as a bonus action."

However, this severely reduces the incentive of the Infiltrators lvl 14 cunning action (cunning action can be used to reload). We'd, instead, like to find places where the Soldier and Infiltrator can reload as a bonus action earlier in their progression tables.

**Comment by bpmcpherson** [comment]
With regard to Infiltrator, the Cunning Action on the reload could be found in a middle-ground area between the current levels (2 and 14). For instance, at level 8, you can use it to reload as a bonus action.

It's earlier in their progression, but not so early that it could be abusable or too easy to dip into if multiclassing comes into play.

**Comment by queryluke** [comment]
Ok, I know I've waffled on this a lot. I finally made a decision. It's so close to a release, that I just decided to run with it, we can make minor tweaks if there are any glaring issues you see.

#### Rapid Reload as variant
Instead of outright removing Rapid Reload, I've kept it as a variant rule, but changed it to a bonus action. This means its not quite as good as having the weapon mod, which simply lets you reload for a bonus action without the check. What I like about this is that using or not using the variant rule doesn't require a bunch of addendums to other mods and class features, like _"if using the rapid reload rule...."_

#### Infiltrators - Fast Hands
Get "Fast Hands" at level 7. This is from the Thief subclass; it lets them reload or use a object (which includes medi-gel and grenades) as their cunning action. To make room, I pushed Evasion out to the 14th level. If I'm being perfectly honest, I think 5th edition is a little busted giving Rogues Evasion and Uncanny Dodge within the first 7th levels. Maybe I'm missing something. But with shields and tactical cloak, I think Infiltrators are evasive enough and the delay of gaining shouldn't hurt too much.

#### Soldiers - Quick Clip
*__I HATE THIS NAME PLEASE SOMEONE COME UP WITH A BETTER ONE__ (or tell me I'm wrong and it's a perfectly fine name)*.

Anyway, quick clip is of my own design and reads:
>You're so familiar with guns that reloading them is nothing more than muscle memory. Once per turn, if the heat of a weapon your holding becomes 0, you can use your Reaction to take the Reload action for that weapon.

What I like about this is that its better than a standard reload as bonus action, and it also provides to potential to reload twice in a single turn (once with this feature and if you have the weapon mod). The other thing I like is its difference from Fast Hands. Infiltrators are crafty, so their ability gives them options. Soldiers are weapon experts so they get a better benefit for their weapons, but no options.

In playtesting, if we find this to be too over powered, we can scale it back to "Choose a weapon" or "Choose a weapon type" and limit it to said weapon or type (which can be changed with training).

**Comment by queryluke** [comment]
Ohh, I'm liking either Tactical or Instinctive reload.

**Comment by bpmcpherson** [comment]
I favor tactical reload.
