### ISSUE TITLE
Biotic Pull "Gripping" a target

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#266]
One of the additions to [Pull in Andromeda](http://masseffect.wikia.com/wiki/Pull_(skill)) (I'm becoming the Andromeda guy) was that the target could be held if the power was maintained. Otherwise, it would function as it did in previous games. The targets were also primed (Lifted).

Now, I suggest adding this to Pull, but that doesn't have to be the case. It could simply be another power (Biotic Grip, which could then include bonuses like dealing damage while being held or ) that ultimately does the following (taken from [Telekinesis](https://open5e.com/spellcasting/spells_a-z/t/telekinesis.html#srd-telekinesis))

> Until the end of your next turn, the creature is Restrained in your telekinetic grip. On subsequent rounds, you can use your action to attempt to maintain your telekinetic grip on the creature by repeating the contest.

Understandably, there's considerations to account for when porting a higher-level spells capabilities to a cantrip in this system, but I wanted to float the idea.

**Comment by queryluke** [comment]
The power of "lifting a target in the air" was originally named "Lift" in ME1, then changed to "Pull" in the subsequent games. But when I designed the spells, I decided it would be better to have a spell named "Lift" because it was more indicative of what the spell actually did (cause the Lift condition).  Pull became something different altogether. It's a simple spell that knocks a target off balance or pulls a weapon from their hands. It's not meant to hold a target in the air.

Thus, if you're looking for a mechanic that lets you hold and move a target, one of Lift's advanced options sort of does this. Also, of note, Lift has been simplified to be a spell attack, not a roll against the targets HP (#119).

**Comment by queryluke** [comment]
I would leave that to the GM's discretion. If I were running the game, I probably wouldn't have it deal damage, but I would make the other creature make a saving throw to avoid being knocked prone.

**Comment by bpmcpherson** [comment]
Gotcha. I just didn't know if collision damage with a surface or creature would apply in this instance (or something like Push).

**Comment by queryluke** [comment]
I've purposefully been vague about how the lift condition works, except for simply allowing other effects to interact with it
>a lifted creature can be pushed, pulled, or otherwise manipulated for varying results.

The primary reason for being vague is because there are too many crazy combinations to try and cover. But the benefit of being vague is to empower the GM to make fun and/or interesting decisions.

Specific to your question
>if collision damage with a surface or creature would apply in this instance

It could, but it depends. If you're playing with a group that hates my loosey-goosey approach, then I'd suggest you apply the falling rules from 5th edition.
>a creature takes 1d6 bludgeoning damage for every 10 feet it fell

So, as long as the creature moves at least 4m, it has the potential to take collision damage. _Disclaimer to any physicists in the room, yeah, I know that's not how it works_

But, personally, as a GM, I would play collisions a few different ways depending on what the player is giving up. Here are some scenarios:

_A Soldier wants to charge a lifted target and slam the target into another one._
In this case, the Soldier is giving up their "bread and butter" extra attacks to make an interesting combat move. I'd probably have the Soldier make an Athletics check (DC 8-10), and, on a success, they knock the target into another one. Both enemies become prone and take 1d6 bludgeoning damage. Damage could be increased if the targets are farther apart. On a failed check, the first target would list gently past the second.

_An Adept wants to use the Pull cantrip to knock one target into another_
In this case, the Adept is certainly giving up some damage potential, but it feels like we're stepping on the toes of the Slam spell. I'd have the second target would make a DEX save to avoid being knocked prone, but it wouldn't take any damage.

_A Vanguard wants to Slam a lifted target into a second one_
I'd let the second target make a DEX save, but if they fail, they would take equal damage to the first target.

But please don't take these examples as law. They're ideas. There are better ideas out there and part of the reason for being vague is to let GMs explore those ideas.

**Comment by queryluke** [comment]
Closing this, further discussion can be moved to #299
