### ISSUE TITLE
Concussive Shot Combo Detonator

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#271]
Concussive shot and Trip Mine are unique in Mass Effect Andromeda in that it is the only Combat Powers to have the ability to detonate primed enemies. In Mass Effect 5e, trip mines (and grenades) are no longer powers, but items, meaning that Concussive Shot remains the only Combat Power that could have that capability. Now, I should state that a few combat powers in the games serve as Primers either through advanced options (Barricade) or general use (Havok Strike/Avenger Strike), so the role is there.

Back to my point. My understanding is that, since Concussive Shot declares that a special ammo magazine/clip is loaded, clips like Warp Ammo cannot be used and thus apply their own priming and detonating effects to the power. So, would it be too much to consider this kind of addition to the power, giving soldier types the ability to better capitalize on Combo Explosions?

**Comment by MonocledMutineer** [comment]
Hi, new guy, made a hello post.

As I see it, it's not the combat types that gains most from Concussive Shot being a detonator, but the tech and biotics. The reason is that while several tech and biotic powers are primers, they also require an action to use, **as does their respective detonators**.

If, on the other hand, you could set up a primer, as say an Adept, and then have your infiltrator buddy detonate it with his sniper rifle on the same round, you would have a good angle on teamwork and knowing the capabilities of the other players. And it would be awesome for the combat types if they could use their bonus actions for something other than just a double tap, such as detonating a force primer and blasting an enemy over a ledge.

With this in mind, I would also suggest that the reset of Concussive Shot is changed from a long rest to a short rest.

**Comment by queryluke** [comment]
I guess I'm ok with this. I was hesitant at first because I feel like this most other classes are limited to how many things they can detonate at within a given turn. I was afraid a soldier with multi-attack would be able to detonate more targets than any other class. But Salvo hits multiple targets and Nova, Flare, and Phase Disruptor can hit multiple targets.

So, overall, I'm ok with this.
