### ISSUE TITLE
"Fighting Style: The Free Hand" Wording

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#275]
"The Free Hand" wording states: "When wielding a pistol, you have a +2 bonus to hit with ranged spell or tech attacks."

Based on the name, I assume that the intention is to reward casters who are *only* holding a heavy pistol with a bonus to their spell attacks. However, with the rules-as-written a character could equip a pistol AND and off-hand weapon, such as a riot shield and still gain the benefit of this fighting style.

If the intention of this rule is to require a character to truly have "a free hand" I'd suggest changing the rule to:

1. "When wielding only one heavy pistol and no other weapons, you have a +2 bonus to hit with ranged spell and tech attacks"
or
2. "You have a +2 bonus to hit with ranged spell and tech attacks whenever you have at least one free hand. To be considered "free", a hand must not be wielding any weapon, cannot be holding (or holding onto) any item, and cannot be restrained in any way"

The second version is much wordier but also allows more clarity and player choice (if that is desired).

**Comment by bpmcpherson** [comment]
I prefer the second one, although you could probably specify one-handed weapon for added clarity. I imagine the idea is that using Pistols and SMGs, which were the basic caster-choice weapons in Mass Effect due to their light weight was the intent of the Fighting Style. Probably should clarify Biotic and Tech Powers since that's the wording of those abilities now.

This style seems primarily geared towards Engineers, Sentinels, and non-shotgun Vanguards. Soldiers wouldn't see any use in this.

**Comment by MonocledMutineer** [comment]
Suggestion:

_"When holding nothing in **at least** one hand, you gain a +2 bonus to hit with ranged spell and tech attacks."_

This holds the meaning of the second option, but cuts down on text and allows the bonus to apply to pistols, SMGs and melee weapons.

**Comment by Duneday** [comment]
First off, welcome to the forum ^_^ Second, its important to keep the flavor and rules consistent with your wording. As a fighting style it is important to maintain that you are wielding a weapon to gain the benefit, therefore the wording should reflect that. As it stands the original writing should still suffice as a shield from your example is still being "wielded" in the other hand, and would therefore not confer its bonus. Much like any melee class using a shield cannot gain its benefits while wielding two weapons.

**Comment by MonocledMutineer** [comment]
I don't agree.

This being an ttrpg and not a preprogrammed crpg should allow players to break with some of the hard ”cannots“ of the source material. I.e we can already dual-wield, something I cannot remember anyone doing in the ME games.

Besides, if I want to play a Vanguard who fights without weapons, using charge, biotic punch and various rangee powers, why should I be chained to holding a weapon that I will never use?

Besides, if you're not wielding any weapons, you have two free hands when you only need one.

As for wielding a shield and no weapon, I will argue that a shield counts as a weapon and so the hand that wields it shouldn't matter. Otherwise the system should re-introduce main hand/off-hand and the sheet should have a box to mark if your character is a lefty. And of course lefties shouldn't be able to use this combat style, because they wield their weapon in ”the other hand“.

Sorry for the extreme example, it's only meant to illustrate my point :)

**Comment by Nmmoriarty** [comment]
@Duneday, Swampson is the Editor-in-Chief of the project.  He should be welcoming you.  :P

**Comment by Swampson** [comment]
@Duneday, I like your wording on this, assuming that @queryluke agrees it fits his intended interpretation. I want to clarify whether it’s important to restrict this style to heavy pistols only other if any one-handed weapon should be allowed.
And thanks for the welcome!  I haven’t been very active lately but am trying to rectify that.

**Comment by queryluke** [comment]
@Swampson @Nmmoriarty 

I should clarify @Duneday's welcome was targeted towards @MonocledMutineer. That person posted on a few issues which have now mysteriously disappeared. This has happened before and the comments reappeared in a few days. I have copies saved and if the original posts haven't reappeared by this weekend, I'll repost them.

**Comment by Swampson** [comment]
Ok, that makes way more sense. That’s what I thought had happened but then assumed I’d made a mistake while re-reading this issue today.

**Comment by bpmcpherson** [comment]
@Swampson I think having it apply to any one-handed weapon is alright. That's basically heavy pistols, SMGs, and some melee weapons.

**Comment by Nmmoriarty** [comment]
Well now I feel like a doofus.

**Comment by bpmcpherson** [comment]
Speaking of @MonocledMutineer, it appears like his account is no longer there. That may explain why his posts disappeared.

**Comment by queryluke** [comment]
They contacted me and said their account was flagged. I told them to contact GitHub support. So hopefully their content will be back soon.

**Comment by Duneday** [comment]
My welcome was indeed towards @MonocledMutineer, I hope support gets him straightened out. On the note of the wording @Swampson I would also like that clarification, it would be a simple change in wording, but important all the same.
