### ISSUE TITLE
Additional Fighting Styles Suggestions

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#276]
Just a few ideas which popped into my head the other day while at work. 

**Close Quarters Shooter**
When making	a ranged attack while you are within 2m of a hostile creature, you do not have disadvantage on the attack roll. 

_Advancement_

When making a ranged attack against a target within 10m of you, your ranged attacks ignore half cover and three-quarters cover and you have a +1 bonus to attack rolls on ranged attacks.

-- OR --

When an attack is made at you with a melee weapon, if you are wielding a ranged weapon, you gain +1 to your AC.

Notes: This is designed for builds which want to be up close and personal, but not focus on shoguns. It's based on the fighting style of the same name from Unearthed Arcana, but tweaked for this system. I was just unsure how to make the advancement. 

**Demolitions**
Add your proficiency bonus to your grenade and mine attack damage rolls.

_Advancement_

The ranges of your grenade and mine weapons are doubled.

Notes: This is for the Demolitions users out there, geared more towards the Demolisher sub-class of Engineer, but also anyone who likes to use grenades and mines.

**Comment by queryluke** [comment]
I'm really unsure about Demolitions. 

1. There are a couple a feats that grant benefits with grenades and mines for those who truly want to use grenades as a primary combat.
2. I feel players with the Demolisher sub-class will feel compelled to take this. If that's our intend, we should just make this a benefit of the subclass.
3. Any player who takes this is going to be spending more money than others because they're focusing on using an item that has a much higher cost than any other. Or, to put is another way, this fighting style is dependent on having an item. Arguably, protection is the same way (barrier ticks) but those don't cost credits.
