### ISSUE TITLE
Starting equipment, Credits and costs.

### ISSUE THREAD

**Issue by MonocledMutineer** [queryluke/masseffect-5e#278]
I played a session this weekend, being at full throttle when the update went live, and we choked a little on some of the changes. The biggest one being the new weapon costs and the changes to damage.

Before I get into it: I really like the whole tier system for weapons, it makes it so much easier to judge the narrative impact of a specific weapon. And the overview buttons are just glorious.

Now I'm sorry, but I must get to it.

**The first problem with the new weapons is the pricing.** As far as I noticed, several weapons have doubled in price, so I assume (the mother of all fuckups) that this has been the approach for most of the weapons.

The issue here is that the racial credit rolls have not changed. For most of them, this means that they can, with an average roll, have either a weapon, or a suit of armour. For some, Geth and Unshackled AI, this means that with an average roll, they may have a Predator, Phalanx, Omni-Torch **or** Riot Shield.

In comparison, taking the class weapons and armour will allow them at least one ranged weapon, a melee weapon and a suit of armour; the last which can be sold for between 8500 (stock light) and 12.750 (stock heavy),

Even the races with the most credits have somewhere between 6000 and 48.000, averaging around 24.000, which is still less than if they take their class-given equipment.

I, personally believe that the prices were better before and that any other equipment that may have promted the increase in price should instead be made cheaper.

**The second problem is weapon damage in relation to enemy shields and hit points.** Because with the new changes, an adept with a M-3 Predator can, at the most, deal 1d4+5 (dex 20) at level 1; and 1d4+8 at the very most at any level, including upgrades.

In comparison, a Cerberus Assault Trooper, some of the first enemies encountered in ME3, while Shepard is still wielding common weapons, has 39 hit points. This means that the Adept, dealing average damage of 7, needs 6 rounds (5.57) to take down a single Assault Trooper, provided that every shot hits.

Of course the Adept's Biotics helps, but they are not a sustainable ressource and cannot carry the fight for the entire Mars mission in ME3, and other classes do not have the same advantage in their powers. In comparison, a mono-blade deals 1d8 damage and is a finesse weapon, allowing 1d8+5 damage, or an average of 9 damage per hit.

I had to adjust enemy shields and hit points a lot during the first session and that was with the old weapon damages.

Now it's not all bad, sniper rifles have been given a much needed boost, which was welcomed by the group's Infiltrator, and myself as well.

**Suggestions**
Increase weapon damages all over the line of ranged weapons and some melee weapons; Omni-torch springs to mind, **or** Reduce the hit points of most enemies by _at least_ 50% and remove the shields of most of them.

Reduce weapon costs by 50%, **or** increase racial credits by the same factor that was used on the weapons costs.

_Sorry for the long post and for being a grump, please imagine a potato ;)_

**Comment by bpmcpherson** [comment]
This got me to run some quick numbers, which are found in [this little Excel sheet here](https://github.com/queryluke/masseffect-5e/files/1981777/ME5e_Race_Credit_Values.xlsx).

> For some, Geth and Unshackled AI, this means that with an average roll, they may have a Predator, Phalanx, Omni-Torch or Riot Shield.

It is true that neither of those races will get as much equipment from their races credit option. That being said, both an innate shielding and armor racial attribute that is equivalent to Medium Armor without a Dexterity modifier cap (same with baseline shields). So, it can be argued that they could use more racial credits to insure that they have access to better weapons, they aren't as lacking as it would seem at first glance.

> In comparison, taking the class weapons and armour will allow them at least one ranged weapon, a melee weapon and a suit of armour; the last which can be sold for between 8500 (stock light) and 12.750 (stock heavy),

This is a key point, that this option is both safer and can earn money back (although I swore that you wouldn't get the full value on a sale, but I cannot currently locate such a rule so I may have made it up!). 

All that being said, I conducted a breakdown to give us an idea of the minimum and maximum equipment values that classes can obtain, as well as a measure of the racial option. It is a good discussion to have if we want either option to be seen as viable in the eyes of players.

**Comment by queryluke** [comment]
Couple of things to parse out.

### Weapons damage and cost
@MonocledMutineer Weapon costs are bound by rarity.
* Common >= 3,000
* Uncommon >= 10,000
* Rare >= 30,000
* Very Rare >= 50,000

However, weapon costs are augmented based on damage profile. The formula @bpmcpherson  mentioned takes the average damage and multiplies it by 1,000. `1d4 = 2.5 = +2,500 credits`

The reason for this is:
1. laziness/variety. I didn't want every single rare weapon to have exactly the same cost.
2. "Fairness". I.e., why does a rare pistol dealing 1d8 cost as much as a rare sniper rifle dealing 3d6?

The problem is that my formula was not using the average damage, it was using the total damage, which is why everything seemed so much pricier. I'll have that fixed this weekend.

### Starting equipment costs
@bpmcpherson Thanks for that spreadsheet. I took it and adjusted the numbers for the new weapon costs. [See new totals here](https://docs.google.com/spreadsheets/d/1ygQzUhjFzPjH_qCdYDStplhVWBxQnFut-O6tRv50mtg/edit?usp=sharing).

Using the updated numbers, max credits for 2 weapons and armor would be something around 20-30,000 credits. Unless you're a soldier, in which case it might always be better to take the weapons.

### Racial starting credits
@bpmcpherson you're spreadsheet is great, but there is a simpler way to look at it:

`avg dice roll * number of dice * 10,000 credits`

Race | Die | Avg. Roll | # Dice | Credits
--- | --- | --- | --- | ---
Long Life Span | d4 | 2.5 | 10 | 25,000
Medium Life Span | d6 | 3.5 | 8 | 28,000
Short Life Span | d8 | 4.5 | 6 | 27,000
Very short life span | d12 | 6.5 | 4 | 26,000

Statistically, long-lived races are going to be closer to the average (25,000), and short lived races have very sporadic ranges. They can peak very high, or fall very low.

### Racial starting credits to buy weapons
My intent was to give players the option of buying a slightly better armor set or uncommon weapon in _exchange_ for having 2 starting weapons. Right now, you could do the latter, but the armor set costs are too high to afford anything but the starter set (unless you wanted no weapons!)

Anyway, I would say this justifies a slight boost. But! We're missing a piece of the puzzle, which is backgrounds. Depending on what those provide in terms of starting credits we could boost or reduce. 

In the interim you could provide a flat starting credit boost (8-10,000 credits) to your players.

### Geth & Unshackled AI starting credits
These 2 have composite plating, so they don't require any armor and don't take the -1 deficit when not wearing armor. So giving them equivalent starting credits, IMHO, would be akin to giving them the option of more/better weapons over any other class.

### Selling weapons back
@MonocledMutineer I think you mentioned, why not just take the starting equipment and sell it back. I plan to have a GM section about this with the credits overview. When I GM, weapons and armor can be sold back from about 1/3 their actual cost. This is entirely up to the GM's discretion, but that's the ratio I'll be using when I metagame other aspects of the system.

**Comment by MonocledMutineer** [comment]
Never be sorry for doing things right :)

The background math looks solid, except for the small blip of counting maximum weapon damage instead of average.

My issue with it is that with the high weapons costs and the, in compatison, moderst racial wealth, rolling for money will only rarely be as good as simply taking the starting equipment. It lacks the benefit that would give the incentive to do it.

Backgrounds may help with this; but since they are not currently available, they are impossible to factor in.

**Selling back equipment**
If I make a Geth Infiltrator and take a sniper rifle and omni-blade from the starting equipment, it doesn't matter that I only get one-third of the light armour's value, it's still a lot more credits than I would have by rolling 2d12 x 1000.

**Penalty for not wearing armour**
My problem here is that I don't understand the reason for this penalty. It breaks the streamlining of the system, adds nothing besides making it near-impossible to put charaters in a fight where they are not prepared for it.

It basically makes it impossible to play characters like Jacob, Miranda, Thane and the various other characters that's not wearing obvious armour.

Even with a dex of 18, which would make for a fair AC (14) for a low level character, the penalty simply negates

**Comment by bpmcpherson** [comment]
Unfortunately, there-in lies the issue with an incomplete system. Without all of the pieces in place, there are going to be gaps that make balancing difficult. 

Regarding the armor penalty issue, at least with regards to your examples, I would safely say that characters like Jacob, Miranda, and Thane are wearing the futuristic equivalent of light armor given their access to shields.

**Comment by bpmcpherson** [comment]
Here's a slight update to my previous spreadsheet, now taking into account the 10,000 Credit bonus. [ME5e_Race_Credit_Values.xlsx](https://github.com/queryluke/masseffect-5e/files/2015036/ME5e_Race_Credit_Values.xlsx)

As you can see, there's a notable increase in that sets the mean values to being really close to the average of the maximum value of choosing the class starting equipment. If you happen to get unlucky with your rolls, it's not going to be enough to offset anything, but that's the risk with taking the racial credit option. 

I think the 10,000 credit bonus helps and my calculations are using the older number and nothing updated or adjusted due to the error in the value calculation.
