### ISSUE TITLE
Fighting Styles, overall concept

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#280]
There has been a lot of discussion about fighting styles: #275 #276 #215 

Before we get too far in the weeds, I wanted to have a brief discussion about fighting styles in general. In 5th edition (including the unearthed arcana), there are 7 fighting styles, 2 of which are very situational (Mariner & Tunnel Fighting). In addition, there aren't any advancement options.

But when looking at the current list of fighting styles, there are a few things that I'm starting to dislike.

__one fighting style per weapon type__
I've fallen into this problem as well. But I think a much more interesting fighting style is one that is applicable to multiple weapons. There isn't really a reason for the Sniper fighting style to be limited to sniper rifles other than forcing a player to choose a weapon type and run with it the entire game. That's not something I want to pidgeon-hole players into. 

__advanced versions__
I originally had advancements because there were no combat powers in the game. So it was want of the few way to "advance" something for soldiers. But I'm finding that unnecessary. Additionally, it makes fight styles extremely difficult to balance. Rather than a single list, there can be a completely game changing mechanic.

__overall, too overpowered__
I feel this is an offshoot of the advanced versions. The first level versions feel fine and balanced, but then we've got to make them better for an advanced version.

So, overall, I'm thinking more generic styles with no advanced versions. But I'd like to hear other people's thoughts. If we did remove the advanced versions, we could certainly open the possibility to learn new fighting styles at later levels.

**Comment by bpmcpherson** [comment]
I think it's okay in some cases to have specialized fighting styles, so long as there are plenty of general fighting styles to offset that. This way, a player looking to, say, focus entirely on sniper rifles can do so while your friendly neighborhood soldier can choose one which benefits his/her entire arsenal.

Regarding the advanced options, it does make it harder to balance, even if some of the benefits were cool. Granted, my translation of the close quarters shooting fighting style from 5e was harder to do because I felt I had to break up the original effect.

**Comment by Duneday** [comment]
Specialized styles are fine by me as most players will usually opt to choose a favored weapon or approach to combat. That said, including a generalist style or two would be welcome for those soldiers or other multi weapon users. 

I believe some of the advanced options offer a nice bump to some builds which would sorely miss them, although there is a fair perspective that some of them push builds too far and make them overpowered. Not sure where I land on that particular issue. Maybe do away with advanced options, but take certain ones and make them class features? Just spit-balling, I'll think more on it.

**Comment by Nmmoriarty** [comment]
Removing the advancement would be fine -- it would certainly make things easier to balance.  That being said, 5th ed is more general only because their categories for things are much wider.  For fighting styles in 5th, generally speaking, all that matters is if your weapon is ranged, a two-hander, or a one hander.  All the fighting style direct you toward a certain type of weapon, since the distinction between weapons in those categories is pretty insignificant (weapon die doesn't vary much, damage type matters very little since very few enemies have a resistance to a particular type of physical damage).

The difference in the system you're making is that there are very few melee weapons, and a lot of ranged ones.  This makes sense that the categories would shift more to favor different types of ranged weapons, which are generally differentiated by their class (pistol, assault rifle, etc).  I don't see it as a bad thing necessarily, but I can see how it might limit people's weapon choices.  That being said, perhaps we could look at the Soldier subclasses Weapon Master and Sharpshooter, which quite specifically push the player to use a single type of weapon all the time if we want to address the idea of golden shackling players into using specific weapons?

Given that fighting styles are largely for Soldiers, and Soldiers are usually all about their weapons, I don't see a problem with a lot of specialized styles.  That being said, having a handful of generalist styles wouldn't hurt, but it would be difficult to balance against the more specialized ones.

**Comment by MonocledMutineer** [comment]
I've been fiddling around with making sone houserules around the various weapon skill advancement options from Mass Effect Andromeda.

I like how you can advance your various weapon types, allowing you to fcus on a single kind of weapon for the entire game.

Granted, it is a little ridiculous that you can research a single pistol (Ushior) and then just go for pistol training and save a ton of skill points.

**Comment by queryluke** [comment]
Ok, sounds like we're for removing advanced options and taking a comprehensive look at fighting styles. I'll open a new ticket with a first pass.
