### ISSUE TITLE
-1 AC Penalty for not wearing a piece of armor

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#281]
@MonocledMutineer brought this up.

>... I don't understand the reason for this penalty. It breaks the streamlining of the system, adds nothing besides making it near-impossible to put characters in a fight where they are not prepared for it.

>It basically makes it impossible to play characters like Jacob, Miranda, Thane and the various other characters that's not wearing obvious armour.

>Even with a dex of 18, which would make for a fair AC (14) for a low level character, the penalty just negates the dex bonus making it useless.

#### Problem 1
My reason for putting it in is that 5th edition's AC calculation for no armor is 10 + DEX mod. In this futuristic setting, "Light Armor" is still a full body suit of armor, its not studded leather. So it didn't make sense (to me), to have someone wearing a full set of light armor only gain +1 AC.

#### Problem 2
The other reason for including it was to avoid the ambiguity of a player wearing 3 pieces of heavy armor but no helmet. What's their AC in this calculation? Should it be 17 for wearing 3 pieces of heavy armor. What about just heavy armor legs and nothing else? Should this person get an AC of 14?

I'm open to suggestions and ideas. The only 2 I have are:

1. Reduce no-armor calc to 8+ DEX mod (but this doesn't fix 2)
2. Have some intermediate rule that states the -1 AC penalty only applies if you're wearing at least one piece of armor.

**Comment by queryluke** [comment]
From @bpmcpherson on #278 

>Regarding the armor penalty issue, at least with regards to your examples, I would safely say that characters like Jacob, Miranda, and Thane are wearing the futuristic equivalent of light armor given their access to shields.

**Comment by MonocledMutineer** [comment]
Let me understand this right:

If I wear a full set of light armour, minus the helmet, I suddently have AC 10 instead of 12?

This brings us back to Miranda, Jacob and Thane, who would, despite wearing futuristic light armour, have an AC of 10 + dex mod, or the same as an **unarmoured** D&D character, while they wear a suit of futuristic light armour.

**Suggestion**
Let the basic armour value depend on the chest piece and make arms, legs and helmets be about mods instead.

The type of armour, light, medium and heavy, haven't been consequential to the game since Mass Effect 1. The thing that really matters in ME 2, 3 and Andromeda is the benefits (mods) that you get from an armour piece. And armour didn't become piecemeal before ME2.

So light armour could give an AC of 13 (free dex), medium could be 15 (max dex +2) and heavy could be 18 (no dex).

Or, if you want the pieces to matter for AC, full light could be 13 (+1 from chest, +1 from arms,+1 from legs), medium could be 16 (+2 from each piece) and heavy could be 19 (+3 from each piece). Max dex could be decided by the chest piece; full from light, +2 from medium and none from heavy.

I don't think that helmets should count on AC, it would force people to wear them, which could just mess with character concepts (Miranda, Jacob, Thane, Jack, etc.)

Which reminds me: Jack isn't wearing armour at any point in ME 1 or 2, does she have AC 6+dex mod?

**Comment by queryluke** [comment]
So, I have to disagree with arguments that use NPCs from the games (Jack, Miranda, Jacob, etc). I suspect the reason these NPCs don't wear armor is because Bioware didn't want to spend money developing new 3d models for them. Well, [unless they could charge for it](http://masseffect.wikia.com/wiki/Alternate_Appearance_Packs). Plus, there are problems with this logic within the game itself. In Mass Effect 3, why does Garrus (clearly wearing armor) have 500 health but Jack (wearing no armor) have 650 health. Sure health is not tied to armor, but there wasn't an armor mechanic for squad members in that game.

Another reason not to reference NPCs is because every Player Character in this game is "Shepard-like," they have as much attention to detail and customization options that Shepard has.

But the base argument is that we're not creating a system that can replicate exact copies of scenes, NPCS, and battles from the games. The discrepancies between the games and trying to meld 5th edition rules onto this replication would be impossible. The mass effect games feature a whole suite of combat mechanics that would be too complex to translate: Rate of Fire, Armor (the third type of hit points), Cool-downs, point-buying for skills. We're looking for a middle ground between 5th Edition and Mass Effect, we're not trying to make a brand new system. So we make changes when they're necessary. 

That being said, is the -1AC penalty a necessary change? Probably not. I'm sure there are better solutions out there.

____

Moving on to your suggestion:
>The type of armour, light, medium and heavy, haven't been consequential to the game since Mass Effect 1.

Correct, but it matters in 5th Edition.

>So light armour could give an AC of 13 (free dex), medium could be 15 (max dex +2) and heavy could be 18 (no dex).

My first issue with this approach is the mental oddity of seeing Player A run into battle with just a heavy armor chest piece (AC 18), while player B is beside them with a full set of heavy armor (still only AC 18). But mechanically, the problem is that players would only put mods on on Light armor, because it's cheaper.

>Or, if you want the pieces to matter for AC, full light could be 13 (+1 from chest, +1 from arms,+1 from legs), medium could be 16 (+2 from each piece) and heavy could be 19 (+3 from each piece). Max dex could be decided by the chest piece; full from light, +2 from medium and none from heavy.

There is certain merit in this approach. Instead of having the array of armor values, we could easily assign static AC bonuses to every armor type/slot. There is still a wrinkle with the combination of medium and light: Light chest piece with medium arms and legs is AC 15 + DEX mod, which would be better than wearing all medium.

Additionally, I would still argue that a helmet should provide some AC benefit. 

>I don't think that helmets should count on AC, it would force people to wear them, which could just mess with character concepts

I don't follow. How does wearing a helmet combat change a character concept?

**Comment by MonocledMutineer** [comment]
Didn't want to what? It's not like they had the models just lying around. I mean, Jacob is muscled and oh so manly, sure, but look at the female characters: Jake is thin, almost skinny, and tough; Miranda is, well ridiculous, but otherwise voluptous and soft; Tali is lithe and waifish. The two that are the most alike is Jake and Fem. Shep, who are both thin and tough.

But! It sounds more like you want a game that is D&D 5E, with a thin ME reskin where everyone is playing Shepard.

That's fine, it's your game and your, very fine, work. But it's not for me. I want a game were my players can be stealthy agents who sneak through a party and fight guards in the side corridors, as well as running through deadly battlefields in full armour.

I'm looking for a versatile Mass Effect game, not ”everyone is Shepard.“

So thank you for your work, but it's premise is not for me. The website is an especially awesome example of how a modern rpg could be presented beautifully and I love the hell out of it.

Thank you for your time, I leave in peace.

**Comment by queryluke** [comment]
Well, I should apologize I gave you any impression that I didn't want you to contribute. I sincerely appreciate differing opinions and when people point out issues. It makes the system better for us to work through them via discussion. This is case in point, I wouldn't have even thought about the -1 AC issue unless you brought it up. My only caveat was that the use of an NPC's model as a basis for defining armor rules isn't applicable.

>Didn't want to what?

I'm not sure what you mean. I assume this is a reaction to my statement about Bioware not wanting to make new models. Let me clarify: They didn't want to create a _standard_ and _armored_ model for each character. I imagine they spent a lot of money designing those character models didn't want to create a new model with armor that covered up the fine details of their character design (like Jack's tattoos)

>But! It sounds more like you want a game that is D&D 5E, with a thin ME reskin ...

Essentially, yes, that is my intent. Though there could be some debate on the "thinness"

> ... where everyone is playing Shepard

This is not my intent. "Shepard-like" does not mean "is Shepard." Perhaps a better term is "unique." The squad members in Mass Effect (NPCs) don't have as many skill options as Shepard just as the NPCs in this game won't have as many class features, racial traits, armor mods as the Player Characters. So, PC's aren't Shepard, but they are more unique and have a wider variety of options. 

> I want a game were my players can be stealthy agents who sneak through a party and fight guards in the side corridors, as well as running through deadly battlefields in full armour.

I agree.  Players that opt not to wear armor are at an extreme disadvantage. I'd like to fix that, which is why I wanted to open the discussion.

Another fix we haven't discussed could be simply providing descriptions about light, medium, and heavy armor, where light armor could be justified as looking like regular clothing (riffing off of @bpmcpherson's point). That's another change I'm open too.

**Comment by MonocledMutineer** [comment]
I see. We approach the game from very different directions; I come from a visual angle, thinking about what the games are _showing_ us, not how the mechanics work. While you, at least seems to, come from the angle of how the game's mechanics are expressed.

It's fine, I shouldn't come in here, stomping around and demanding changes. You've put in a lot of work and, as I will keep saying, made a fantastic website to host it, me not liking some parts of it shouldn't really matter.

So! Sorry for being a, slightly angry, pain and best of luck, to all of you, with the project :)

**Comment by Duneday** [comment]
While not as passionate I do have to agree that it seems a bit wrong to say a normal person in normal clothes is somehow easier to hit simply because they aren't wearing armor. The whole point of a baseline AC is to have just that: a baseline (an unarmored normal person), which dnd and d20s establish as a 10+dex mod. Putting the negative on seems unnecessary to me.

While your second suggestion (only applying the negative if wearing any armor) would address part of this it then becomes a bit odd that putting on a piece of armor would somehow apply a negative to your  AC. Id say a pretty straightforward solution would be breaking up AC contribution across the specific parts the armor is covering as Query and Mutineer had previously discussed. Your concern with the medium and light wrinkle is notable, but I see no issue with it in the long run a full medium armor build should be taken to maintain a minute amount of invested Dex. The light chest piece here should grant more AC in this instance because that player invested in Dex as an attribute where the medium armor user could have invested elsewhere, the opportunity cost was paid elsewhere so I see no problem with it. Aside from that you could also see about applying the max Dex like the armor bonus, as a slot-by-slot rather than as a full set (Light chest Max Dex+2, Legs +2, Arms +1 Full set no limit/ Medium Chest +0 max dex, Medium Legs +1, Medium Arms +1/ Heavy +0 Max dex everywhere) Something like that, just a suggestion off the top of my head.

**Comment by queryluke** [comment]
I've been playing around with ideas @Duneday & @MonocledMutineer and thinking through any possible issues. Here is my proposed overhaul of the armor system:

### Proposal

* Each armor piece  has a set +AC.
* For Arms, Legs, & Chest, this is based on the type of armor (see below)
* Helmets don't have a type (light, medium, or head), instead some helmets will provide +1 AC and some won't.
* +DEX bonus is only based on type of armor you're wearing (completely ignores helmets because they don't have types)
  * No heavy or medium armor pieces =  +DEX
  * At least 1 medium & no heavy pieces = +DEX (max 2)
  * At least 1 heavy piece = No Dex bonus, disadvantage on stealth
* Additional Changes
  * _Full Suit_ armor and head pieces (in the armor sets) will need to list the provided AC if helmet provides the +1 bonus.
  * _Full Suit_ prices will need to be adjusted to accommodate helmet price "squish"
  * Add clarification that _Full Suit_ armor are integrated, meaning they only work if all 4 pieces are worn.
  * Custom head armor will have a single starting price
  * Add some flavor text about light armor and how it can be as light and free-flowing as clothing.

__AC Bonus matrix__

Armor Type | Chest | Arms & Legs
--- | --- | ---
Light | +1 | +0
Medium | +2 | +1
Heavy | +3 | +2

### Thoughts

Overall, this still provides the necessary range of AC within 5th edition boundaries

Armor | AC
--- | ---
No armor | 10 + DEX
Light armor | 11 + DEX
Medium & Light | highest possible is 13 + DEX (max 2)
All Medium | 14 + DEX (max 2)
Medium and Heavy | 15 & 16
All Heavy | 17
Helmets | _some_ will provide +1 AC

* With the flavor text, we're changing _light_ armor to mean specialized clothing and not heavy gear. I'm ok with that and it justifies the limit jump of +1 AC. 
* Removing helmets from the AC calculation remedies problem 2. Players who want max AC will still opt for helmets. Some may argue this makes them "required." I would counter it depends on the player and if they are metagaming or if they are roleplaying (e.g., a narcissistic character who doesn't' want to mess up their hair). Either way, at max helmets will only provide an additional +1 AC
* Finally, this also solves any mixing issues, as the +DEX is limited by if you put on a single piece of the next tier of armor. This somewhat forces players to choose an armor tier and stick with it, but mixing isn't even in 5th edition so you're always forced to stick with an armor tier.

The only downside I'm seeing right now (and please point out other flaws if you see them), is that this change would be a slight nerf to heavy armor. I can remedy this for starting equipment by having the Stock Heavy Armor include a helmet with +1 AC.

**Comment by Swampson** [comment]
One additional thing that I think is worth explicitly clarifying in the rules is whether it’s allowed to mix-and-match different armor for each arm and leg. This is one of those things I don’t think would be an issue 90% of the time, but it’s worth accounting for edge-case scenarios.
- _Can_ a different type of armor be equipped on the right arm/leg than what is on the left?
- If so, how does this affect the AC matrix?
Personally, I’m in favor of stating that “arms” is a single slot, as is “legs”. I think it prevents unnecessary complications in an already detailed system.

**Comment by Duneday** [comment]
A little confused by the wording in terms of what is actually contributing to AC. For example if you wore an entire set of light armor would your AC be 11+ Dex or would each piece have its own AC contribution based on the equipment itself, if so what is the purpose of the matrix, is it just a bonus for wearing entirely light in this case?

**Comment by queryluke** [comment]
@Swampson 

Good point. My intention is that there are still 4 slots: head, chest, arms, legs. But the +AC bonuses from arms and legs are the same based on if they're light, medium, or heavy.

@Duneday 

The +AC comes from the individual armor pieces. It's completely mix and match. +DEX is not a factor. Examples:
* light chest(1), light arms(0), no armor (0) = 11 AC
* light chest(1), medium arms(1), light legs(0) = 12 AC
* medium chest(2), medium arms(1), medium legs(1) = 14 AC
* heavy chest(3), medium arms(1), medium legs(1) = 15 AC

The +DEX is limited by the highest type of armor type you're wearing. The logic would be
* if you're wearing at least 1 heavy piece, you have disadvantage on stealth checks and have no DEX bonus...
* otherwise, if you're wearing at least 1 medium, you get a maximum of +2 AC from your DEX mod...
* otherwise you add your DEX mod to your AC (i.e., not wearing any medium or light)

Using the examples above, the final AC would be:
* light chest(1), light arms(0), no armor (0) = 11 + DEX
* light chest(1), medium arms(1), light legs(0) = 12 + DEX(max 2)
* medium chest(2), medium arms(1), medium legs(1) = 14 + DEX(max 2)
* heavy chest(3), medium arms(1), medium legs(1) = 15 AC (disadvantage on stealth)

**Comment by Duneday** [comment]
I get the Dex limitations just fine, its pretty much treat your armor type as though it were the heaviest piece you're wearing. My confusion had arisen from where your totals for AC were arising from (What values were assigned to basic armors per slot and type). 
Though if I understand this correctly everything should even out to 5E given full sets of the same armor type + a helmet (Light armor would come out to 17 with a dex mod of 5, Medium: 15 +2, and heavy flat 17).
