### ISSUE TITLE
Asari and Asari Biotics

### ISSUE THREAD

**Issue by MonocledMutineer** [queryluke/masseffect-5e#283]
I have a few questions about the intention with Asari abilities;

**Innate Biotics**
If I make an Asari soldier, can I take the _Barrier_ cantrip? And if so, how many barrier ticks do I get?

If I make an Asari biotic, do I add the 1st level power to my normal list of powers, or do I get the watered down version from the ability?

**Skill Versitility**
You do realise that with this ability, an Asari can have eight skills by level four? Three from their class, two from this ability and three from the _skilled_ feat.

Isn't that a bit much compared to the other races?

**Comment by queryluke** [comment]
RE: Barrier
With rules as written, you could take it, but you wouldn't get any barrier ticks because the soldier class doesn't have barrier ticks. We add a note on the barrier power or in this section about it. But honestly, I'm fine with the RAW version.

I'm not sure I understand your question. What is the "watered-down" version. The "only able to cast 1 per long rest". Then, yes, that spell you're only able to cast once per long rest. This would be the same in 5th edition for a Wizard who took the Magic Initiate feat.

RE: Skill versatility
I don't see a problem with this. A lot of the other races get an additional skill proficiency, which would allow them to have 7 skills by level 4. If a player wants to sacrifice combat potential to be a skill monkey, I'm ok with that.
