### ISSUE TITLE
Spell Review: Barrier Detonation

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#294]
from #284 

## Current
* Level: Cantrip
* Casting Time: bonus action
* Range: self
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
Expend all of your remaining barrier ticks to create a negative mass effect field in a 2m sphere originating from you. Each Medium or smaller creature or object within the sphere must succeed on Dexterity saving throw or becomes lifted

Increase the range of the sphere by 2m at 5th level (4m), 11th level (6m), and 17th level (8m).

__Advanced Options__
* Shaped Lift: You may choose the shape of the detonation
* Heavy Lift: Large and smaller creatures and objects are affected.

## Thoughts
* No benefit over using more than 1 barrier tick.
* Only spell that has a prerequisite

One possibility is to remove it and make as an advanced option of barrier, or just an optional component of barrier.

**Comment by TheMarmotKing** [comment]
This being a component of barrier makes sense.  I would avoid it as an advanced option as doing so would essentially change nothing except making it advancement instead of spell.  You would still have to spend a spell opportunity learning it.  
Suggestion for advanced option if this is made a component of basic barrier: 
When barrier is depleted, automatically cast barrier detonate as if it consumed x(some balanced number) of ticks

**Comment by Swampson** [comment]
I also think we should consider having Barrier Detonation be a an actual _detonator_ since it’s right there in the name.
