### ISSUE TITLE
Spell Review: Biotic Punch

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#295]
## Current
* Level: Cantrip
* Casting Time: Attack
* Range: Touch
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
Increase the mass of your fist and strike at a target. Make a melee spell attack on a target creature or object within range. On a hit, deal 1d8 bludgeoning damage to the target and gain 1 barrier tick per size of the target (1 for small, 2 for medium, 3 for large, etc.)

At higher levels: This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), 17th level (4d8)

__Advanced Options__
* Efficient Punch: Gain an additional barrier tick when you hit a target with your Biotic punch
* Syphoning Strike: Instead of gaining a barrier tick, you regain 2 shield points per size of the creature.

## Thoughts
In this case, I'm not sure the advanced options are equivalent. Efficient Punch seems much better than syphoning strike.

**Comment by TheMarmotKing** [comment]
An advancement option making it a bonus action would be an equal choice

**Comment by bpmcpherson** [comment]
I like siphoning strike (typo in your spelling) as it is an actual mechanic used by vanguards in the games to supplement their defense while getting up-close. Perhaps the scaling can instead be tied to their damage so that the shield gain will increase as the character levels increase. 

Another alternative is to consider looking at passive abilities like the ones found in Andromeda and integrating them into the classes. For instance, Vanguards often have [Barrier](http://masseffect.wikia.com/wiki/Barrier_(skill)), which has a tree designed to supplement Siphoning Strike by making kills with biotic attacks (charge, biotic punch) grant shield power.

**Comment by queryluke** [comment]
### Proposal
* Level: Cantrip
* __Casting Time: Action__
* Range: Touch
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
Increase the mass of your fist and strike at a target. Make a melee spell attack on a target creature or object within range. On a hit, deal 1d8 bludgeoning damage to the target and gain 2 barrier ticks.

At higher levels: This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), 17th level (4d8)

__Advanced Options__
* Efficient Punch: On a hit, gain 3 barrier ticks.
* Siphoning Strike: On a hit, instead of gaining barrier ticks, gain 10 shield points.

## Thoughts
* Before, as an attack, there was no reason to use melee weapons, so making an Action adds a limitation to how often this spell is used.
* Removing the "per size of creature" keeps the spell simple. Most of the time it would be 2 BTs anyway.
* 3 BTs is 13 dmg reduction average which isn't quite equivalent to 10 shield points. But the siphoning strike makes this spell viable to builds that don't make heavy use of Barrier.
