### ISSUE TITLE
Spell Review: Catapult

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#304]
**Current**
* Level: 1st
* Casting: Action
* Range: 20m (30m line)
* Duration: Instant
* Detonates: No
* Primes: No

**__Spell Text__**
Choose one object weighing less than 10 kilos (about 20 lbs.) within range that isn't being worn or carried. The object flies in a straight line up to 30m in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. In either case, both the object and the creature or solid surface take 3d10 bludgeoning damage.

At Higher Levels: When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 2 kilos (5lbs), and the damage increases by 1d10, for each slot level above 1st.

**__Advanced Options__**

* Option 1
Salvo:
You can choose any number of objects as long as the total weight of all objects chosen does not exceed the maximum amount of weight for the spell. Each object can be sent in a different direction, but only deals 1d10 damage.
* Option 2
Delayed Catapult
When you cast this spell, you may delay the launch of the object. It hovers 2m off the ground until you launch it. You may use a reaction or bonus action to launch the object. If launched as a reaction towards a target making an attack roll, you imposed disadvantage on that roll.

**Thoughts**

Balance wise I have no issue with the spell and Delayed Catapult.  However I think that the spell text needs some clarification.  I can't tell what happens on a successful dex saving throw.  Do they take half damage?  or does the the object keep moving and they still take full damage?  
**Recommend:**    If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving, and both the creature and object take 3d10 bludgeoning.  On a successful save, both the object and creature take half as much damage, and the object will continue moving, either until it collides with another creature, a solid surface, or exceeds the range of the spell.

As the the advanced options, I actually love both of these as they are really creative and interesting options.  But as a player who loves to abuse wording, Salvo needs a fix.  
"you can choose **any number** of objects as long as the total weight of all objects chosen does not exceed the **maximum amount of weight** for the spell."  
I'm sure you can see where this is going,  because the first thing I'm going to do is pick up 20 1 pound bags of sand and dish out 20d10 bludgeoning damage (half as much on a successful save) to the entire room.  
what say we limit this to 5 small objects at most.  
I would also change the wording from""but only deals 1d10 damage" to "the damage is reduced to 1d10"
Overall, I like this spell.  It's versatile, interesting, and fun.

**Comment by wolfesamk** [comment]
Agree that spell text does need some clarification. Also agree that what happens on a dex save. The wording implies to me that if the Target makes the save, they dodge the object. Like you said, Half-Damage on a successful save covers the what happens in that instance, but one thing still bothers me.

The line "If the object would strike a creature" implies an attack action. May need a rewording as a whole for the hit/damage section. Possibly along the lines of the fireball spell in 5e. 

FIREBALL
"Each creature in a 20-foot radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one."

CATAPULT
A creature within a 30m line from the objects starting point must make a Dexterity saving throw. A target takes 3d10 bludgeoning damage on a failed save, or half as much damage on a successful one.

Another thought I had was why not turn the Salvo option into a Cone damage radius, where the max number of affected targets is equal to the number of objects you can pick up. Number of items can be linked to casting stat + something to show greater ability at higher levels, maybe even a simple "Number of objects equals casting stat + casted spell level." Since this spell is level one, and your casting stat is supposed to represent your innate skill with that spell class, the Salvo option will level along with the damage output of the spell. Total weight of the objects would still be limited to the one set by the basic parameters of the spell.

**Comment by queryluke** [comment]
This is one that I scavenged almost directly from 5th, sans the advanced options. I upped the damage and weight of the objects since there was no effect if the target succeeds on their saving throw.

I can only speculate, but I think there are a few reasons as to why the target takes no damage on a successful save:

__Non AoE__
Fireball explodes in an area so being near it (even if you get out of the way) isn't enough to completely protect you. With Catapult, the object either hits or misses, it deals damage in a very tight area.

__Damage to the object__ 
Note that both the object and creature take the damage. In 5th, at higher levels you'd be able to fling an small creature. And that damage will always hit. So the primary effect of this spell is a nascent 3d10 damage to something plus an opportunity to damage another creature.

I think the designers of 5th created this spell for its variety and interaction with the environment. A player might pick up a locked chest and smash it against a creature or wall, opening the chest. For ME, you might pick up a barrel of oil, smash on a creature and the DM could reward that any creature within X meter radius is now covered in oil or the air is difficult terrain. A creature might drop their weapon and you could pick it up and smash it against a wall to destroy it. Thus the spell has much more utility.

So, I'm leaning against the addition of half damage on a successful save, but am still open to it. In theory the creature barely gets out of the way and gets clipped by the object, taking half damage, but the object still continues (as @TheMarmotKing suggested).

Another possibility is to increase the damage, making this a more high-risk/reward option if used as an attack on a creature.

Finally, salvo is a bit broken in its current form. I think @wolfesamk's option of adding a limit to the number of things you can pick up is a good idea (i'm thinking based on spellcasting mod 1-5). In that case, there would be no need to reduce the damage on each one.

**Comment by queryluke** [comment]
## Proposal
* Level: 1st
* Casting: Action
* Range: 20m (30m line)
* Duration: Instant
* Detonates: No
* Primes: No

__Spell Text__
Choose one object weighing 1 to 10 kilos (about 2 to 20 lbs.) within range that isn't being worn or carried. The object flies in a straight line up to 30m in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the creature and stops moving. When the object strikes something, the object and what it strikes each take 3d10 bludgeoning damage.

At Higher Levels: When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 2 kilos (5lbs), and the damage increases by 1d10, for each slot level above 1st.

__Advanced Options__
* Salvo: When you cast Salvo, you may target a number of objects equal to or less than your spellcasting modifier. The combined weight of the objects cannot exceed the maximum weight limit of the spell (10 kilos at 1st level, 12 kilos at 2nd level, etc).
* Counterstrike: You may cast catapult as a reaction when you see a creature within 30m of you casting a spell or making a weapon attack. If the creature is casting a spell, it automatically fails its Dexterity saving throw and must succeed on a Constitution saving throw (DC 10 or half the damage done by catapult, whichever is higher) or the spell fails and has no effect. If the creature is making a weapon attack, you impose disadvantage on the attack roll whether or not the creature fails its Dexterity saving throw.

## Thoughs
Added a clarification on resolving the spell and added a minimum weight limit (no throwing tissues!)

_Salvo_: Limited the number of objects. This creates potential for 15d10 damage from a 1st level spell. But each salvo requires a Dex save and a failed Dex save means no damage. It also requires there be 5 1-4 kilo objects lying around that the player can see.

_Counterstrike_: The issue I had with Delayed Catapult was the double action cost. Action to set up then a bonus or reaction for the payoff. With a minor benefit of a reaction causing disadvantage. That seemed too steep a price, given the alternative is the possibility of 15d10 damage. What I like about counterstrike is that it provides Biotic users a Counterspell mechanic but can also be used against a standard attack.

**Comment by TheMarmotKing** [comment]
Salvo has a good limit now, and the spell if defined clearly.  Counterspell seems a bit out of place though.  I think a biotic counterspell warrents it's own spell, maybe at level 2? 

Proposal for advanced option:
Boomerang
If the object does not hit any targets, it will halt at the end of it's path.  As a bonus action for the next minute you may cause the object to return to you as if you had cast catapult on it.

**Comment by queryluke** [comment]
The mental image I had with counterstrike was:

_Player A sees an Adept start to cast Singularity and quickly scans the room seeing a small toolbox. Before the Adept can finish casting Player A hastily flings the toolbox in the direction of the Adept. The Adept is so busy with their casting, they are automatically hit by the toolbox. Depending on how advanced the Adept was, the strike might even prevent them from finishing their casting_

I think the boomerang idea is really neat, but I also wanted to avoid any continued control over the target. With the increase in weight from high spell slots, it would be possible to eventually catapult a creature, so I was trying to make this a one and done action.
