### ISSUE TITLE
Barrier (I Know -_-)

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#318]
Back to Barrier woooo hoooo.  So I think the current version is actually pretty good.  Fixes a lot of issues.  However, It does also create more resource issues (which I'm sure would be balanced in the future with or without my bringing it up).    This might need playtest data, but considering that there are 3 or 4 spells that need barrier to work and the maximum charges for the first few levels rest at 2 or 3, I don't feel like you get enough of barrier.  For Vanguard and Sentinel, who will be taking the most hits, those charges will run out very quickly, and abilities like Nova and barrier detonate will be weak, just due to the lack of ticks.  For Adepts, who are most likely not going to be using biotic punch to get back those ticks, but also not be in range to use nova or barrier detonate, they can use it for phase disruptor and damage reduction and not much else.  And that's a very limited pool of shots. 

I know it's not a topic we want to keep picking at, but I propose that we change it to a short rest recharge and see what happens.    

Lastly, and this could be a huge point in balancing barrier, didn't the damage reduction used to scale with levels?  and if not, I think it should.  1d8 damage reduction at higher levels is a drop in the bucket.  Strongly recommend increased it as levels go up.

**Comment by queryluke** [comment]
>For Vanguard and Sentinel, who will be taking the most hits, those charges will run out very quickly

Since Barrier can be a bonus action, in a single turn, the player can always cast a max barrier ability like nova. But! I agree that this constitutes a very high resource cost. For me, the question is if the damage of a max, barrier tick-fueled power is worth a bonus action AND a spell slot. I'll have to run some number on each barrier-fueled power to answer that question.

>I know it's not a topic we want to keep picking at, but I propose that we change it to a short rest recharge and see what happens.

Yes, I agree this would be a simple and easy change provided a look at the numbers.

> didn't the damage reduction used to scale with levels?

It sort of still does. Sentinels and Vanguards get __Heavy Barrier__ at later levels: 

>Whenever you take damage while barrier is active, remove 1 barrier tick and reduce the damage by 3d8.

And battle master vanguards have the d8 increased to 10, 12.

For adepts, I agree that 1d8 is minimal at higher levels. But this was the intent. It's at least some reduction, but not enough to be a staple of the adept's repertoire.

**Comment by queryluke** [comment]
@TheMarmotKing With the change to Nova, is the only remaining piece deciding on a short or long rest? Did you want to revisit damage reduction?

**Comment by TheMarmotKing** [comment]
I'm satisfied with the changes
