### ISSUE TITLE
Healing Rework Potential

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#33]
There is currently no info for the Healing Surge feature showcased in the Shaman subclass for the Adept. I suggest replacing this ability and all biotic healing abilities entirely (the only other one I have noticed so far is Regenerative Bolts) , making Tech the branch of powers that is responsible for healing, as in the games. I realize this means that the Shaman needs to be reworked. I'd suggest replacing Healing Surge with the Improved Barrier feature from the Protector Vanguard, as the Shaman seems like they are supposed to be a tankier support Adept.

This means that if a party needs healing, MediGel and MediGel related abilities (i.e. Unity) become the go-to method. An example of this might be treating MediGel like a renewable healing potion; it starts in limited uses for the party at level 1 (such as 1 use of a Minor Healing Potion), but classes like Sentinels and Engineers would be able to improve the quality of their team's MediGel dice size, or boost the amount of times MediGel is accessible by the party per long rest. Something like that. 

Similarly, an ability like Unity could use all of the technician's MediGel to act as the spell "Revivify", which revives a dead character if cast within 1 minute of their death if I recall correctly.

**Comment by queryluke** [comment]
First: Thanks for contributing! 👍 

Healing is something I've been tinkering with a lot. We noticed in the play test that it didn't make sense, lore-wise, for Adepts to be able to put HP back on. So we ended up quick-fixing and saying the mass effect fields adepts generate could recharge shields. Any healing spell became a shield regen spell. But I'm not a huge fan of that concept either.

It definitely makes sense for the Sentinel (echoing a paladin) to have some healing mechanics. I'm leaning towards scrapping both the Shaman (Adept) and Paladin (Sentinel) subclasses, substituting a battlemage-esque and healing role, respectively.

You're right that there is currently no mention of medigel. My current plan is that characters have a medigel capacity, that can be increased with armor upgrades. The medigel would be a consumable, like a potion, but instead of giving you a flat HP gain, it would allow you to use one of your hit die. So, more common than a health pot, but has the limiting factor of the number of hit die a character has.

I also really like the idea of Unity and increasing the medigels effectiveness. That's definitely something I'll look into for the next version.

**Comment by SleightxHope** [comment]
Thanks for the response! Mass Effect is my favorite game franchise, and I'm about to run my players through their first session in a week using this system. (Warning: incoming wall of text)

My suggestion for the Adept's subclasses would be to consider basing them on three types of Wizard/caster roles; namely, Blasting (concentrating on offensive output), Controlling (concentrating on battlefield control) and Crippling (concentrating on debuffing the enemy and inflicting statuses). 

I would change the Justicar's subclass name to Kineticist (since Justicar is a title and wouldn't apply to a character with similar powers but no Justicar code). I would recommend swapping the Dominate ability at levels 10 and 18 with the ability Biotic Orbs. This new subclass would give powers that turn the Adept into a "biotic artillery" that focuses on consistent damage.

For the Shaman, I would change the name of the subclass to Blackstar (sounds cool, indicates that the majority of their powers are gravity/eezo based). I would swap the defunct Healing Surge (levels 2 and 14) with Biotic Sphere, which used to be at levels 10 and 18. Where Biotic Sphere once was (levels 10 and 18) I would place Singularity.* This would make the Blackstar Adept a battlefield controller that can punish enemies for entering spaces and restrict where they can move. 

*For Singularity's Advancement, I would replace the Heal advancement with the following:

Heavy Singularity: When a creature affected by this power makes a DEX or STR save to avoid its pull, they make that save at disadvantage. 

Finally, for the Fury I would consider re-branding this subclass in several ways. I suggest that all of the "dark" abilities (clearly based on Javik's powers) be renamed, as Protheans would be non-playable in 99% of circumstances. The powers may still be chosen as biotic abilities, but should probably have an aesthetic name that reflects more standard biotic users.

I would reclassify the Fury as the Disruptor (since their abilities would be focused on debuffing, crippling, and making life generally miserable for their enemies). The subclass would look like the following:

2  Quick Biotics
 
6  Reave
 
10  Dominate 
 
14  Reave, select an Advancement option 
 
18  Dominate, select an Advancement option 


Here's how I would reclassify the "dark" adept spells:

Dark Channel = Biotic Tether, Dark Sphere = Flux Cannon. They keep their original effects, just get renamed.

------------------------

As for the Sentinel, I think that the Battlemaster and Bastion could use minor tweaks, but let's leave those alone for now. This will just focus on the Paladin, which I think can be renamed (ideas are Guardian, Intercessor, or Field Medic) and focus more on keeping his team alive. Assuming that MediGel would work as you described and typically only be 1x use until replenished (at a ship or 1st Aid Kit) and would do 1dx (X= class HD) healing per use, I recommend the power set look like the below:

2   First Aid
 
6  Unity*
 
10  Kinetic Boost (formerly Regenerative Bolts)
 
14  Unity, select an Advancement option 
 
18  Kinetic Boost, select an Advancement option 
 
-------------

Again, this is all just suggestions, I'll probably be implementing some slowly as we go with our campaign. Let me know if anything is helpful!

**Comment by queryluke** [comment]
Hey! All of these are great ideas, I'm going to make comments on the rest of the issues as I work through them. I wanted to say, first, I hope the campaign went well! And second, at the risk of screwing things up, I've been working for the past 2 months on a MAJOR overhaul of this system. Don't worry, I'm going to keep the current site alive so all the information in v0.1.0 will live on in perpetuity.

Anyway, one pattern that I started getting rid of was pairing abilities with sub-classes, because, with such a limited number of spells/power, taking just a few out of the pool really limits options for players.

Though I hope to have "beta" up in a week or so, my responses below can serve as a bit of a preview. Obviously none of it is set in stone 😄 

----

### RE: Adepts
 I took a lot of your ideas for adepts (blast, control, crippling). Love the name "Blackstar," btw.

For renaming the "dark" abilities, I generated most spell ideas from the ME3 multiplayer classes. Though Dark Sphere was only available to the awakened collector, I liked the idea of some adepts being able to wield [dark energy ](http://masseffect.wikia.com/wiki/Dark_energy), and these would definitely deal necrotic rather than force damage. But a more important reason to not rename them is that I really want to expand the spell list, and "Flux Cannon" and "Biotic Tether" have some serious potential for new spells!

----

### RE: Sentinel Healing class
I took your idea for Unity (thanks!) and made it tech power available to sentinels, engineers, and infiltrators. 

Instead of a straight healing class, I gave Tech Aura a bit more flavor (AI subroutines running in your part members' armor systems), but also gave it more versatility. Now, when you cast it, you get to choose which buff (aura) you want to run. I also created a feature called Omni-Shield. Basically, you get _shield mastery_ & _protection fighting style_ from D&D for the duration. But, honestly, I still think the Sentinel class needs the most work (and that was my main in the original trilogy!)

----

### Engineers
I also scrapped a lot of the Support subclass and added some fun talents that revolve around healing. Including "Medi-gel Enhancements" which lets an Engineer add buffs to medi-gel uses.

**Comment by SleightxHope** [comment]
Hey, thanks for the feedback! I helped my players create their characters last week, this Wed they start the campaign proper. No worries, I already let them know that if we have to ret-con their powers, we will because it's all playtest material. It's all good!

Re: Adepts

I see where you're going with the "dark" powers, and I think that's awesome. Perhaps additional subclasses for each class could be made as time goes on, and a Fury class could focus on stopping enemies' regenerative powers with necrotic/fire damage (future Krogan, Vorcha builds, etc.)

Glad you like the Blackstar! I think that a good way to look at each subclass is to see if there's a role/archetype that each one can fill to bring something to the team. I'll offer some more suggestions/thoughts on subclasses at the end of this comment thread. 

Re: Sentinel Healing Class

I like the idea of turning the Paladin Sentinel into more of a Bard, with Tech Aura acting like a Bard's song. Different buffs happening with different auras, etc. Yeah, the Sentinel seems like it'd be hard to balance, because of the versatile nature of the class. 

Re: Engineers 

I see, that's pretty cool! I'm thinking that maybe the Support Engineer (or another class as an ability) might be able to recharge heat sinks as an option. For my players, they can each bring 4 heat sinks for free into a fight, and each additional heat sink they bring after that takes 1 unit of STR to carry. Something to make that easier might be fun to mess with.

My thoughts on goals for future/other subclass goals:

One of my players brought up the idea of turning a subclass into more of a "Skill Monkey", and I think that the Saboteur can benefit a lot from this. My suggested rework of the Saboteur subclass only changes a little:

SABOTEUR INFILTRATOR:

2  Expertise- as the Rogue skill, you may double your proficiency bonus for 2 skills that you are already proficient in. You get another 2 skills (or hacking/repair kit proficiency) again at level 10.
 
6  Eye for Detail 
Insightful Fighting 
 
10  Expertise   
 
14  Infiltration 
 
18  Saboteur's Touch (Once per long rest, when an enemy makes a saving throw against one of your abilities that imposes one, you can make them fail the saving throw.) 
 
This would make them a bit more thematic as far as becoming masterful social/mechanical infiltrators, causing their enemies misfortune in new and unorthodox ways with their powers of observation and (eventually) imposing bad luck on their enemies. You can make the Shadow Broker feature into a background.

As a side note, I'd adjust the Ghost slightly to get away from tying powers (like Shadow Strike) into subclasses. See below:

GHOST INFILTRATOR:

2  Efficient Cloak 
 
6  Uncanny Dodge 
 
10  Supreme Sneak-  you have advantage on a Stealth check if you move no more than half your
speed on the same turn.
 
14  Evasion 
 
18  Ever Vigilant- You can take two turns during the first round of any combat. You take your first turn at your normal initiative and your second one at your initiative -10.
 
This turns the ghost into more of a sneak/evade/survive type of Infiltrator, a' la the Thief archetype.
 
Another change that I think would be helpful is a rework of the Operative. I think they were inspired by the Mastermind Rogue archetype, but I think it'd be better as a subclass of the Sentinel. Think of Miranda Lawson, who is effectively a Sentinel without tech armor. She's a leader, giving orders from the front instead of using stealth. Having a Sentinel subclass that uses superior Heads Up Display tech to give the Sentinel a tech aura that lets them give split-second tactical info to their allies (Help action). I'd adjust the Sentinel/Infiltrator subclasses as follows:

Overwatch Sentinel

2  Master Tactician 
 
6  Misdirection 
 
10  Biotic Enfilade- If an ally within 10m uses a power that primes an enemy, you may use your reaction to detonate the primed enemy with a quick biotic bolt that cannot miss. The enemy takes an additional 1d6 force damage as per the detonation rules.
 
14  Master Duelist 
 
18  Synchronized Assault- Once per long rest, you may use a reaction to sync the targeting computers of all your allies who are conscious, and can make an attack with a weapon. As an action, you target an enemy, painting them with an infared beam that lets all of your affected allies (and yourself) make an attack roll on that target using their weapon during your turn. If your affected ally has already taken their turn, they may still make an attack on the designated enemy, and if they have not yet taken their turn, they make the attack with advantage.

This is how I'd change the Operative too-

OPERATIVE INFILTRATOR:

2  Dropshot- You have advantage on attack rolls against any creature that hasn’t taken a turn in the combat yet. In addition, any hit you score against a creature that is surprised is a critical hit. 
 
6  Deadeye- You may spend 1 TP to gain advantage on an attack made with a Sniper Rifle by overclocking your scope's targeting technology. 
 
10  Combat Heuristics- Every time you bring an enemy to 0 HP or score a critical hit on them with a Sniper Rifle, your HUD updates your tactical feedback, restoring 1 TP each time this occurs. 
 
14  Tracer Rounds- When you hit an enemy with any kind of special ammo, you and your allies have advantage on attacks made against them for the next 1d4 rounds. Once an enemy is marked this way, you cannot use this ability again until you take a long rest. 
 
18  Killshot- When you attack and hit a creature that is surprised, it must make a Constitution saving throw (DC 8 + your Dexterity modifier + your proficiency bonus). On a failed save, double the damage of your attack against the creature.

This makes an Assassin archetype style Infiltrator. I know this is all subject to change, just let me know if there's anything you want to use!

**Comment by queryluke** [comment]
Going to start breaking these into separate tickets for ongoing discussion.

**Comment by queryluke** [comment]
Closing this for now, the Overwatch Sentinel was moved to #40 and all of the infiltrator ideas relocated to #39, #41, #42

**Comment by queryluke** [comment]
As a final button on this thread, I just threw the "beta" iteration of classes and class features onto the [README](https://github.com/queryluke/masseffect-5e/blob/master/README.md). Not a great way to consume the info, hence the reason for the site itself.
