### ISSUE TITLE
Omnitool Programs

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#331]
Although the spell review is still going on (to be followed by class review), I thought it'd be good to bring up a fun New idea.  

Presenting: Omnitool programs.
One time use programs for a variety of uses from hacking, speed boosts, or even casting spells.  

Programs are intended as a flavored version of spell scrolls and consumables like potions. 

Here are a few easy ideas.

Decriptor key: automatically open one lock or gain access to one system without making a hacking check

Acceleration program: enhance speed for a brief period
Camo program: deploys a temporary camo field to boost stealth
Defense boost: grant resistances through armor or something
 
You get the idea.  Names are improved because Luke's much better at comming up with them.

Lot's of easy copy paste from E5, adds a new level of consumables that players can get creative with and save up money to buy.

Share your thoughts, and don't worry I'm not super beholden to any aspect of this idea

**Comment by queryluke** [comment]
I think this is a great idea! It can fill the void of Wondrous Items from 5th edition.

**Comment by bpmcpherson** [comment]
Sounds like a pretty solid idea to me. Maybe have them consume some sort of item (i.e. omni-gel) for certain ones.

**Comment by bpmcpherson** [comment]
Late addition, but the micro-fabricator idea I talked about some time ago would fit within this. It's a function of an omni-tool, but clearly something which was first shown in Andromeda so it may be something one has to install.

**Comment by SleightxHope** [comment]
Been thinking about this, and have a list of possible "wondrous items" that can be replicated by Omni-tool programs. Might want to treat an Omni-tool like a "spellbook", where you have to 'learn' a program to be able to use it, and there's only so much storage on a tool for combat programs like these. Here's a few, more incoming but I'm at work rn lol.

Their rarity corresponds to that of wondrous items, and can be represented in-game by the more common ones being programs that common mercs and hired guns might be able to afford, while the rarer might be military level tech or an arms manufacturer's experimental program. Instead of "Attuning" to these items, you can only have 3 "Active" processes running at once for balance:

Reactive_Kinetic_Compensator.exe (Uncommon): A faster-than thought program that generates a burst of hard light between the layers of the user's armor to reduce trauma from otherwise-lethal hits. When the user is hit by a critical hit, the user can spend their reaction to activate this program and turn it into a regular hit. Requires 2 Omni-gel to activate, can be activate once per long rest.

Cardio_Muscular_Optimizer.exe (Rare, must be Active ): A program that syncs up with the user's VI to run a full-body performance optimizer. Your CON score is 19 while you are running this program. It has no effect if your CON score is already 19 or higher.

Trace_Signal_Jammer.exe (Uncommon, must be Active): While this program is Active, the user is hidden from long-range sensors. You cannot be targeted by any tracking device that functions by receiving a tracking device's signal, and targeting lasers cannot pinpoint your precise location, giving you advantage on any saving throws against their attacks.

Experimental_Barrier_Grenade.exe (Rare): The user of this program can, as a bonus action, convert 4 Omni-gel into 1d4+4 black beads that measure 3/4ths of an inch in diameter but weigh nothing. These beads are held in place on the user's wrist by the Omni-tool's hard light field. 
 As an action, you can launch a bead up to 30m. The bead explodes on impact and is destroyed. Each creature within a 6m radius of where the bead landed must make a DEX saving throw or take 5d4 Force damage. A sphere of transparent biotic energy then encloses that area for 1 minute. Any creature that fails its save and is completely within the area is trapped inside this sphere. Creatures that succeeded their saves or are partially within the area are pushed away from the center of the sphere until they are no longer inside it.
Only breathable air can pass through the sphere's wall. No attack or other effect can.
An enclosed creature can use its action to push against the sphere's wall, moving the sphere up to half
the creature's walking speed. The sphere can be picked up, and its altered mass causes it to weigh only 1 lb. regardless of the weight of creatures inside.

**Comment by SleightxHope** [comment]
More Omni-tool programs:

Primal_Tap.exe (Rarity varies, must be Active): While this program is active, your Omni-tool perfectly balances your adrenal, muscular, skeletal and cardio systems to optimize physical power. Depending on what Mark program you have active, your STR score increases to a certain amount. This has no effect if your STR score is already equal to or higher than that value. Many military groups equip their combat-ready infantry with a version or Mark I or II, but more up-to-date versions of the program are incredibly rare to find, the bleeding edge of military technology that only the best can afford.

Version- STR Score- Rarity
Mark I- 21 - Rare
Mark II- 23 - Very Rare
Mark III - 25 - Very Rare
Mark IV - 27 - Legendary
Mark V - 29 - Legendary

-------------

Echo_Cancel.exe (Uncommon): When you activate this program, spend 1 Omnigel to activate a specifically attuned mass effect field in your armor's boots. This field is keyed to sound waves, and while the field is active (duration is 1 hour) your footsteps make no noise. You also have Advantage on Stealth checks that rely on remaining silent. 

------------------

Double_Time.exe (Rare, must be Active): While this program is Active, you can use a bonus action to re-route a third of your Omni-tool's processing power to your armor's mobility servos, dramatically increasing your speed. You double your walking speed, and any attack of opportunity made against you is made at Disadvantage. This effect lasts 10 minutes, and can only be activated once per long rest. 
(this re-route wasn't intended by any armor manufacturer, the recovery time allows the Omni-tool to scan and repair the abuse electronics within the armor.)

-----------------

Spotter_Support_System.exe (Uncommon, must be Active): While this program is active, your Omni-tool links up to your armor's gauntlets, scanners, and weapon systems. Roughly a third of its processing power is diverted into calculating micro-corrections when you fire at a target, generating minuscule magnetic fields to align your aim more correctly. You are considered proficient with Sniper Rifles while this program is Active, and gain a +2 to damage rolls with such weapons. 

--------------------

Deflector_Array.exe (Rare, must be Active): Developed by technicians who wanted more protection while maintaining light armor, while this program is Active your Omni-tool generates a form-fitting nano-cloud of hard light atoms around your armor, invisible to the naked eye. This increases the chances that an incoming bullet or attack will be turned aside by the nano-cloud, acting as an extra layer of protection. 
The user gains +2 to AC while not wearing Medium or Heavy Armor, or using a Riot Shield. (Anything bulkier than Light Armor throws off the cloud's bio-tracking, and renders it ineffective.)

--------------------

Cycle_O2.exe (Uncommon): Spend 1 Omni-gel to hermetically seal/harden your hardsuit against vacuum/underwater pressure. While most armors act as space-suits, they aren't necessarily graded for more than a few minutes of vacuum exposure, nor are they graded for underwater performance where water pressure can be crushing. 
Activating this program effectively grants the user Water Breathing and the ability to breathe indefinitely in zero-oxygen environments until the end of their next long rest.

-----------------------

Quantum_Displacer.exe (Rare): Spend 3 Omni-gel to fuel a highly experimental quantum device in your armor. You can spend a bonus action to designate an open space within 60m, and instantly teleport there (as the PHB spell 'Misty Step'). 
You project one invisibly small molecule into that space, which is quantum entangled with a molecule in your armor. Sending an energy current through the device will re-unite the molecules instantly, effectively teleportation you to your designated location. The device is then offline until the end of your next long rest.

-----------

Thermic_Overvent.exe (Uncommon): You can use an action to spend 2 Omni-gel and overheat every heat-generating element within your Omni-tool, overriding safety protocols and using the Omni-gel as propellant. You create three fire rays from your outstretched hand, each with a range of 240m. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage. When you make the attacks, make them with a modifier of +5 to the attack roll. The Omni-tool then needs time to compensate and repair itself, rendering this program inoperative until the end of a long rest.

------------------

More later but it's 2:15 AM here lol.

**Comment by queryluke** [comment]
Great as always. I'm really excited to include these in the next release.

My only concern is the permanent AC & attack/damage bonuses. I've balanced all the weapon and armor mods to make sure that AC & attack/damage bonus can't exceed a +3** keeping them in line with 5th's magic items. If we add omni-tool programs that provide additional permanent bonuses (getting into the > +3 range), I'm worried of breaking 5th edition's bounded accuracy. I totally fine with temporary bonuses, +X for a turn used once per long rest, or something like that. 

But I haven't perused the magic items in 5e. I know they have +1-3 weapons and in rare cases legendary items with a +4. So if there are cases of permanent bonuses for damage/attack rolls from magic items, I could be completely wrong. I'm less concerned about AC (deflector array), but I'm wondering if using other mechanics like disadvantage on attack rolls for a limited time might be an alternative.

** As I wrote this, I noticed combining high-caliber with stability dampener gives a +6 bonus. Then I checked my notes and found that high-caliber barrel is only supposed to be +damage and not +attack roll. I'll need to fix that.

**Comment by SleightxHope** [comment]
I ripped the Deflector Array stat boosts from the 5e DMG item Bracers of Armor, which gives non-armored or lightly armored characters more AC in exchange for one of their possible attunement slots, which I think is decently balanced if you don't let that stack with med/heavy armor. 

As for the spotter_support_system, that's basically Bracers of Archery but instead of bows, it makes you proficient in/more damaging with sniper rifles. I don't think it breaks anything too badly, since it essentially does the same as the Archery fighting style from the PHB and doesn't affect bounded accuracy at all. It also makes peculiar builds like sniper Adepts or Engineers possible, which helps people get more out of their build by sacrificing attunement spots.

Ultimately it's up to you, but it's definitely in the main game of 5e to make people sacrifice versatility for optimization. If a player wants to make a character that does '-all-of the sniper rifle damage, they can, but they'll sacrifice all the other cool stuff their Omni-tool programs can do. Always appreciate your feedback man. =)

**Comment by queryluke** [comment]
Thanks for the clarification! I will concede that I am completely wrong then :)

**Comment by SleightxHope** [comment]
Lol no probs man, we all want the same thing: an awesome game!

Flash_Hypno.exe (Uncommon, must be Active): This program, while Active, programs strobes in the user's visor/eyewear with 3 powerful charges. You can expend 1 charge as an action to cast the 'Charm Person' spell (save DC 13) on a sapient creature within 30 feet of you, provided that you and the target can see each other. Your Omni-tool regains all expended charges after a long rest, provided that the program is Active. 

-------------------

Zoom_Enhance.exe (Uncommon): As an action, you can spend 1 Omni-gel to activate this program. The  Omni-gel is flash-forged into delicate, fine-tuned lenses that fit over your armor's optics, enhancing your ability to see minute details. You have advantage on Intelligence (Investigation) checks that rely on sight while searching an area or studying an object within a range of 2m for 10 minutes before the lenses fall apart. 

-------------------

All_Terrain.exe (Uncommon):  As an action, you can spend 1 Omni-gel to flash forge hard light enhancements for your armor, such as climbing spikes on your boots and gloves, and flexible fins on your boots. While running this program, climbing and swimming don't cost you extra movement, and you gain a +5 bonus to Strength (Athletics) checks made to climb or swim for 1 hour.

----------------

Expert_Hand.exe (Uncommon, must be Active): While this program is Active, the user's Omni-tool optimizes their gauntlets' mobility and sensitivity. Many operators and infiltrators prefer this program, as it makes their jobs much easier. While Active, you gain a +5 bonus to Dexterity (Sleight of Hand) checks and Intelligence (Electronics) checks made to bypass locks.

----------------

Night_Sight.exe (Common): A standard night-vision program issued to infantry across the galaxy. Your optic sensors now have darkvision out to a range of 120m. If you already have darkvision, activating this program increases its range by 120m. 

-----------------

Cognition_Booster.exe (Uncommon, must be Active): This program diverts positive energy from your Omni-tool to the nerve clusters in your brain, accelerating your thought processes and critical thinking. Your INT score becomes 19 while this program is active. If your INT is equal to or higher than 19, this program has no effect.

------------------

Trying not to include any wondrous items that fall too far outside the established lore.

**Comment by queryluke** [comment]
again thanks @SleightxHope for all your work. These are all in #382. We can open new issues for new ideas.
