### ISSUE TITLE
Background of L2 Biotic (and others)

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#358]
Given that I'm playing through Mass Effect 1 again, it occurred to me just how much being an L2 human biotic can affect your character's history, personality, reputation, etc.

I think such backgrounds could be useful in story telling and there would be benefits and consequences. 

For instance, L2 biotics are stated to be far stronger than most L3+ biotics to the point that they are comparable to an asari's natural proficiency. The catch, of course, being health issues from minor (migranes) to complete mental disorders. 

If a background would not be the appropriate way to implement this, then another way can certainly be done. I just figured it would make for a neat mechanic with plenty of background to go with it.

**Comment by queryluke** [comment]
I like it! There are a few options of implementing something like this:

#### Background
Maybe, is there a prerequisite of being human (or _not_ being asari). I don't think there are prerequisites for background in 5th edition, but that doesn't mean we can't do it.

#### Feat
This is an interesting idea. There are instances of racial prerequisites of feats (Xanathar's Guide to Everything introduced some). The feat could be: Charisma is your spellcasting modifier for biotic spells. Maybe some other additional benefits like "Cha +1", and possibly a detriment. It certainly gives some additional Cha availability as a spell casting modifier, and it wouldn't need to be limited to Humans.

#### Subclass
The one that speaks to me most is a subclass for humans. It could also provide CHA as a spellcasting modifier, some other benefits (drawing from Asari race), but have a few hindrances as well.

**Comment by bpmcpherson** [comment]
Subclass for humans seems like a better course of action, now that you mention it. The reason I specifically mention human is that the "L2 biotic" was a human thing during their early development of biotic implants.

**Comment by SleightxHope** [comment]
I like the human-only subclass idea, "L2 Adept". Its class abilities could almost act like the Blood Hunter for 5e (Matt Mercer's popular homebrew class) where you trade HP for increased offensive output. 

Subclass features could include something like the following:

Overclocked Amp: As a bonus action, you may choose to deal 1d4 Psychic damage to yourself in order to add 1d4 Force damage to all biotic spells that deal damage for the next minute. 

This can scale with level. Thoughts?

**Comment by queryluke** [comment]
Whoops, I actually meant sub_race_. But either could work.

__Subclass__
I've always wanted to include more subclasses since the number of classes is limited. My only concern is that the player chooses a subclass around 2nd/3rd level. It doesn't break the game, but it does break the character's story a bit.

__Subrace__
My initial idea was a subrace of human. It's not a true subrace, but it would be described as a human that has an extremely high innate ability for biotic casting. When lends to giving them CHA as their spellcasting mod.

That said, I really like the __Overclock Amp__. It could work for either a subclass or subrace.

**Comment by SleightxHope** [comment]
I propose a background like the following to give a bit more freedom for roleplaying:

"Experiment"
Skill Proficiencies: Science, Survival
Tool Proficiencies: Tinker's Tools and your choice of Medical Kit, Disguise Kit, or Chemist's Supplies
Equipment: A set of common clothes, a trinket from your program of origin, Tinker's Tools, and 300 credits.
Feature: What Doesn't Kill You- You were the subject of experimentation in your youth, with the goal of stripping away the old you and turning you into a weapon. The program could have been funded by your race's government, a shadow organization, or a single mad scientist who kidnapped you. It could have had the goal of turning you into the ultimate soldier, perhaps an unrivaled biotic, or even a genius tech engineer. 

Regardless of the program's nature or success, you survived your difficult trials and came out tougher for it. You've been pushed to the edge of death before, so it doesn't scare you. Once per long rest, you can choose to make a death saving throw with advantage due to your strong drive to survive.

Thoughts?
