### ISSUE TITLE
Shields and Spells

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#376]
This came up as I was reviewing Cryo Blast. In all four Mass Effect games, spells and powers typically do not effect shielded targets. This is something I've sort of address with the "Unprotected" condition. There a some spells in the current RAW (Beehive, cryo beam, cryo blast) that reference the unprotected condition. But its not used enough to justify it as a separate condition.

The other issue is figuring out what happens when a spell shouldn't effect a shielded target. I.e., casting Pull on a target with shields, are they immune to Lift? I've avoided tackling this because I don't want to add a by-line on every spell: "If the target has shields..."

My current idea is to give shielded targets advantage on the saving throws and give ranged spell attacks disadvantage. Examples:

__Pull__
Make a ranged spell attack on a Medium or smaller creature or object within range. You have disadvantage on this attack roll if the target has at least one shield point. On a success, you create a mass effect field around the target and it becomes lifted 2m in the air...

__Singularity__
Create a negative mass effect field in a 4m sphere at a target location within range. Each creature or object within the sphere's radius must succeed on a Strength saving throw or becomes lifted. A creature with at least one shield point has advantage on this saving throw...

While it doesn't have true parity with the game, it references the in-game mechanic while also making shield points more than just regenerating HP.

**Comment by TheMarmotKing** [comment]
I like this because it makes shields more than just extra hp.  But there needs to be very clear indication on spells if shielded targets get advantage.  Also, I know armor was a big thing in Mass effect as another form of "extra hp" but I'd recommend not bringing armor into the mix in terms of interacting differently with spells.  It's too much in my opinion.  Especially since shields, barriers, and other layers of how can be tricky to track as is.  

Another nice thing about this is that it gives biotics a reason to use guns not just spam biotics.
