### ISSUE TITLE
Major class changes?

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#378]
@bpmcpherson @TheMarmotKing @SleightxHope

I know we just came up with the memory/load system for tech powers and we haven't even put it in the game. But I've been working on an idea that I think has major benefits for simplifying the entire spell structure.

__Tech spells use spell slots__
Get rid of the tech point system and have tech spells use the spell slots. Seems like a bad idea, but as I started experimenting with it, the idea fixed a lot of underlying issues. From a design standpoint, spells and classes become much easier to balance. From a player standpoint, it reduces the number of new things a player has to learn and, while I personally like the intricacies of the memory/load tech point system, I think it might be a bit too complex.

My first concern was that classes would feel to similar. This was the reason I created the tech point system way back in v0.1.0. But after working through the idea I don't think class similarity is a problem.

### Summary of classes
Here are the [proposed class progressions](https://docs.google.com/spreadsheets/d/1_lvUpjK9LVYa1I7JafcsKWxFU-1YiJzAhTUuhowrkm0/edit?usp=sharing).

__Adepts__
- They're sorcerers without the sorcery points.
- They learn/advance spells & cantrips as they level up. Spells are always at their disposal.
- They regain spell slots on a long rest but have "arcane recovery"
- They get access to the most cantrips out of any class.

__Engineers__
- They're druids but with tech (sorcery) points
- They know all the tech spells but are limited in the number they can prepare (Engineer level + Int mod), and the level at which they can prepare those spells (their max spell slot). advanced versions of a spell count as 2 spells. I.e., a 3rd level engineer with 3 int mod can prepare 6 spells, or 3 advanced spells, or anywhere in between.
- They gain "Flexible Casting" allowing them to create spells slots in exchange for tech points
- Tech points will give them new and interesting ways of augmenting spells or other class features (like drone)

__Infiltrators__
- Still rogues, but innately "Arcane Trickster" rogues.
- They know all the tech spells but are limited in the number they can prepare (half infiltrator level + Int mod), and the level at which they can prepare those spells (their max spell slot). advanced versions of a spell count as 2 spells.
- They're half-casters, meaning the only get a maximum of 3rd-level spell slots
- They learn/advance combat powers like cantrips

__Sentinel__
- They're bard/clerics
- They learn tech _or_ biotic spells as they level. But they must prepare those spells (sentinel level + spellcasting mod)
- There will be a (possibly optional) rule that allows sentinels to use Wis or Int or (possibly) Cha as their spellcasting mod. We've discussed this at length before, but tech and biotic used different resources. With tech & biotic using the same resource, spell slots, then it makes less sense for them to have a stat split.

__Soldiers__
- Unchanged...they're fighters

__Vanguard__
- They're warlock/barbarians
- They have a limited number of spell slots, but they always cast spells at the highest level.
- They can learn combat powers instead of cantrips (their choice).

## Thoughts
Overall, I know these are major changes and not everybody will like them. However, my primary motivating factor is reusing the mechanics of 5th edition (and all the balance and playtesting it benefits from) rather than writing our own.

And I don't think this makes the classes too similar. There are 3 full casters (engineer, sentinel, adept), but each has a slight variation on how they learn/prepare spells (based on 5th edition variations). Plus they each have their unique class talents. There is one half caster, infiltrators. And one "weird" caster, vanguard. Then your basic class, soldier.

**Comment by TheMarmotKing** [comment]
There are a few big pros and cons about this system.  I'll preface this with the statement I'm not in favor of this change. I'm in favor of keeping tech points and I'll explain why below.

Pros: simplicity- It's easier to manage the mixed classes if they all use spell slots.  It makes it a game of simply balancing slots rather that all these other mechanics.  
It also makes it less of a new system for people to learn.
Con-loss of unique class feel.  
I have since, finding this system, thought the idea of tech points was a great meld of spells and the monk/sorcerer point system.  I don't think it's a complex idea to grasp for e5 players and I think it adds a level of complexity to the game the makes it fun to play with.  The versatility of tech points is refreshing and the addition of load makes it more balanced.
Additionally, many of the tech classes use tech points for class abilities, giving them a lot of different playstyle options.  Infiltrators using tech clock to sneak around or using spells to deal out more DMG.  Sentinels using tech armor over and over or comboing with biotics.  Engineers focus on drones or spells.  I think taking tech points away and making them short rest limited would make those classes less fun.

This is just my 2 cents on the topic, And from a creator standpoint it might be easier to rebalance to an all spell slot system.  But regardless I am open to ideas

**Comment by queryluke** [comment]
Thanks for the feedback. I'm still working through a lot of the details, and people's concerns really help me dig in. Seriously, I can't stress enough how much it helps when people disagree with me :)

### RE: Class uniqueness
I agree, there is some loss to class uniqueness. The big hit is engineers, but there are some pieces that, I hope, would still make them unique. First, they're the only full caster that can swap out their spells on a long rest. Adepts & Sentinels learn a spell "for life". Adepts always have access to all their spells, Sentinels are limited in the number of spells they can bring to battle (limited by spell level). Between Adepts, Sentinels, and Engineers, the "Spells Known and Prepared" mechanic is a shuffle of 5e full casters (Wizards, Sorcerers, Clerics, Bards, Druids).

The second piece that sets Engineers apart are the tech points. I haven't written any powers, but the tech points will grant them some unique features. Thus, I feel like Engineers remain the most versatile full caster.

Additionally, Vanguards get a substantial change that I think adds uniqueness to the overall class system. (side note: whether or not I implement this in full, I think that might be a piece I keep).

### RE: Infiltrator tech point powers
- Tactical cloak: This is basically the Invisible spell in 5e. So its basically a free 2nd level spell. That, by itself, is really powerful. My thought was limiting by prof bonus per long rest, but I'd also be ok with prof bonus per short rest.
- Operative: Deadeye & Combat Heuristics: These would need to be changed, but I'm sure there are interesting subclass features we could create.
- Shadow strike: I didn't have this on the sheet (since added), but my thinking is that instead of costing 5 tech points, it would cost 1 charge of tactical cloak. It ends with tac cloak active, so you're really just getting an awesome movement bonus every time you cast tac cloak. If that is OP, it could cost 2 charges of tac cloak (kind of how Circle of the Moon druids can become elementals for both of their wildshape charges). 

### RE: Sentinel tech point powers
- Tech armor: Sentinels are already limited in the number of times they can cast tech armor per long rest (equal to their prof bonus). So this change would buff tech armor (because it doesn't cost a resource anymore).
- Bastion: Tech Armor Overload - I'd probably just remove the tp cost, since the player is sacrificing the tech armor to make the effect happen. So, again, a minor buff.
- Advanced Tech Armor - doesn't really change, you still get 3x the spell slot level in additional hp for your tech armor.

### OP early level Engineers
As I've been simulating some character builds with the tech spell review and memory/load system, I did find another balance issue. Consider a 2nd-level Engineer with INT = 16. Their memory would be 5. Which means they could load an advanced Flamethrower (essentially a 4th level spell). That's at least 7d6 damage for a 2nd-level character. They can only cast it once, but at 2nd-level that could clear a room.  There are certainly adjustments I can make in how their memory scales. But the easiest solution is adding another limiter like: "At 1st-level, you may only load 1-load tech powers, ...at 8th-level, you can load X-load powers..." And at this point, we're basically in the spell slot system.

### Deeper dive into engineers
All that said, one thing I _really_ liked about the new memory/load system is the versatility and granularity it gave engineers for which spells they had prepared. There were three aspects of this versatility:

1. _Swapping out spells on a long rest_. This still exists in the proposal.
2. _Beefing up spells for tech points_. This sort of exists in the proposal. Engineers can create a spell slot in exchange for tech points. So if an engineer wants to cast Incinerate at 5th level, they can make a 5th level spell slot for tech points. This is part of the __flexible casting__ mechanic that will be reused from sorcerers. It's not exactly the same as beefing up a spell you're casting, because it takes a bonus action. But those are rules I'm willing to bend. I.e., engineers might get some talent that says: "When you cast a spell , you may spend 2 tech points to increase the potency of that spell. The spell becomes 1 spell slot higher than the level you cast it at". Side note, this example would open up casting as 6th-level for engineers, another unique factor.
3. _Granularity of spell choices_. I did a bit or simulation on the following spreadsheet, and the proposal adds even more granularity. The only piece that is lost is the granularity of when you increase spell power using more tech points (again, this can be compensated with engineer features as in point 2).

I created a [spreadsheet with a possible loadout for a 10th level engineer with 20 int](https://docs.google.com/spreadsheets/d/1xhPBil93ft-NzjpeNR0M8VzST6TRUSciCpolJAH2lEo/edit?usp=sharing).

The two major takeaways:
- Proposed system will always give engineers more spells in their toolbox
- Memory/load system can cast more higher level spells. _But_ this is more than compensated with __Flexible Casting__

After really breaking this down, I'm not sure the memory/load system offers any more variety/granularity than what 5th edition spell slots offer. It has a look & feel of a unique spellcasting ruleset, but mechanically, its starting to look subpar to the existing 5e spell slot system.

**Comment by queryluke** [comment]
Based on comments fro #379, I added a new Sentinel sheet to the proposal. In the __Sentinel 2__ sheet, sentinels become more like paladins. They are half-casters and they learn spells as they level (no spell preparation needed). I think this makes Sentinels less like "adepts-with-tech". Though, their spellcasting becomes limited, the fighting style, quick cast, and extra attack features make them much more viable as weapon users.

**Comment by BenutzernameIstBereitsVergeben** [comment]
I dont actually think that the current system is difficult. Once you have grasped it, its pretty elegant, especially because it stays the some over all the hybrid classes. The new proposal somewhat muddies it in that the hybrid classes dont necessarily cast the same as the base classes, which is odd.

**Comment by TheMarmotKing** [comment]
I spoke to a few of my players (the engineer and the sentinel) about tech points in general vs spell slots.  They both like tech points from a standpoint it adds a nice flavor to tech vs biotics that helps flesh put the difference between the two as well as combat abilities.   I think having the 3 separate systems for each type really emphasis their unique roles as class types. Having a different system (load and tech points) also offers a kind of new aspect for players to enjoy rather than just porting e5 spell casting.  While it's ultimately not up to me, I think the tech points are a really well fitting and we'll made part of this system and I'd hate to see them go, especially with the new load system being made

**Comment by queryluke** [comment]
@TheMarmotKing 

I've been tinkering with a middleground. Keeping tech points, but not implementing the load mechanics.

Tech spells would have a spell level. But what that level means for the class types (biotics vs tech) are slightly different.

__Engineers__
Engineers would keep their 50 tech points. To cast a spell, they have to pay points equivalent to the spells level. They can cast higher versions of the spell for additional points. For example, Incinerate would be a 1st-level spell, but they could spend 2 tech points to cast it as a 2nd level spell, 3 for 3rd, etc.

This is really only a thin veil over the spell slot system. But it does offer more versatility than my above proposal. First, biotic casters have fixed spell slots, but engineers would have a sliding scale. For example, a 20th level adept has one 5th-level spell slot. But a 20th level engineer would have up to 10 (5 points to cast a 5th level spell).

So the primary difference is that Engineers have burst damage. They can blow all of their tech points early (then be SOL), or reserve them overtime. Whereas adepts and limited by their spell slots.

The only thing I have yet to figure out is how to prevent preparing high level spells at lower level.

__Infiltrators__
Same as engineers, with less tech points.

__Sentinels__
One criticism I have of the current RAW is that sentinels feels like multiclassed engineers and adepts. The half-caster proposal breaks away from this, focusing on a "paladin-like" build. If tech spells have spell levels, I think I would remove tech points for sentinels. Instead, they'll use spell slots to cast tech spells.

This leaves 2 tech point classes (Engineer-full, infiltrator-half), 2 spell slot classes (adept-full, sentinel-half), and the vanguard changes using warlock spell progression.


Does this fix any of your concerns?

**Comment by TheMarmotKing** [comment]
Lot of items to change though.  So tech spells have a spell slot level and a tech point cost? Or engineers use tech points to cast spells?  And then what about tech point cost values, do sentinels just ignore that part of the spell?    I'm just thinking out loud but I kind of feel like whatever change is made, tech spells need to have the same casting mediums for all classes that use them.  Otherwise it might be too confusing.

**Comment by queryluke** [comment]
@TheMarmotKing 

I was thinking that all spells (tech & biotics) would only have a spell level.

Vanguards, Adepts, and Sentinels would use spell slots to cast spells (as normal).

Infiltrators and Engineers would use Tech Points. 1 tech point = 1 spell slot. But it gives these classes more versatility. Instead of being limited to 1 5th-level spell slot, they could burn all of their tech points to cast 10 or they could cast 50 1st-level spells, or anywhere in between.

**Comment by TheMarmotKing** [comment]
Would infiltrators and engineers use tech points for drones and cloaking as well?

**Comment by queryluke** [comment]
Drones yes, cloaking no. I want to limit the number of uses of tac cloak per short rest. But I'm not completely sold on either.

**Comment by bpmcpherson** [comment]
Sorry I haven't been able to reply when this was made. In any case, I think the goal of a simplified casting system is a good one. I want to say I suggested something in the past which suggested doing something like this (perhaps for the debate on Charisma being used, but I don't recall).

I think the most difficult aspect in this change will be how to handle your hybrid classes to not make them feel gimped by the change while still not being better than their non-hybrid bases. For instance, Sentinels are a jack of all trades class as far as the Mass Effect series goes, with the real difference between the builds of Sentinels being either power focused (thus, a support-like role) or weapon focus (capitalizing on additional bulk to be a tank). The pivot of all of this being the tech armor playing a key role in what makes them stand out from either an engineer or adept.

Similarly, Vanguard and Infiltrator capitalize on having Charge/Nova and Tactical Cloak respectively. Personally, I think this is the key to uniqueness for these classes. Additionally, if you wanted to have a Sentinel be far more of a caster (as in forgo much of the tech armor for just tech and biotic casting) a subclass can be used to alter the class appropriately. Same with having an infiltrator acting more as an N7 shadow rather than a sneaky sniper.

**Comment by queryluke** [comment]
class changes abound in #382 

any issues/wants/needs can open new issues
