### ISSUE TITLE
Assorted views on the game

### ISSUE THREAD

**Issue by BenutzernameIstBereitsVergeben** [queryluke/masseffect-5e#379]
I hope opening a thread and just dumping my thoughts in it is usefull, it seemed more apporopiate than writing an e-mail, and for most things there are no open thread discussing it. 

Full disclosure: Although I have played lots of RPGs from FATE to DSA to LotFP to Pathfinder, I only have limited experience with 5E. I have also not played all that much ME5E, some of what I am writing is theorycrafting.

General: 

I really like the Spell System, props for that. The different categories feel very distinct, which also carriers over to the hybrid-classes. Since the spells are very combar focussed, the typical martial-caster gap doesnt really exist. 

The powerlevel on lower levels seems somewhat higher than in 5E, and Monsters thus seem somewhat underwhelming. They would need to be buffed. At the same time you may think about moving a bit away from 5Es high-hp, low dmg monsters a bit. 

In 5E, your ability to customize characters is somewhat limited. Which doesnt matter all that much, because there are 12 classes with many very different subclasses. In ME5E on the other hand this is a problem. The 6 classes are very different from each other, but there are still only 6 of them. Some subclasses are great, other feel similar. There simply isnt enough intra-class difference. Its a hard problem to solve though. Some ideas would be to de-couple feats and ability score advancement and give yout more feats. Another soloution would be to make each weapon category more unique, but later more to that. 

Classes: 

The Infiltrator has a shit ton of options to gain an advantage and sneak attacks. I like it, but it certainly is stronger than the Thief. 

The Sentinel is somewhat overlooaded. Why does it have Quick Cast and a Fighting Style when neither base classes  are weapon-focussed and have it ? Stuff like that would better be moved to a Subclass.

Soldier: Can you learn Combat Powers twice to get extra uses ? Overall they get very few combat powers, especially compared to the Infiltrator. 

Vanguard: The Nemisis subclass combined with dash and/or biotic punch somewhat bypasses the action and barrier economy, and I am not sure this is intendet. 

Gear: 

Some upgrades are way to strong (Archon AI,  or weak (Damage Reroll) for their price.  

The weapon categories are somewhat uninspired. There is no real difference between some Heavy Pistols and Assault Rifles and Sniper Rifles. I think it would be good to have a unique weapon quality that only weapons of that cat have. 

Why do Shotguns of all weapons lack an AOE attack ? Another problems with them is is that they basically require Close Combat Shooter as a Fighting Style due to their low range. 

Burst Fire is only usefull if you have the Assault Fighting Style, due to the scaling of it. If you do have it seems very, very strong however. 

I do have some Ideas about different weapon styles if it is wanted.

**Comment by queryluke** [comment]
Thanks for the feedback! I've put my thoughts below.

>The powerlevel on lower levels seems somewhat higher than in 5E, and Monsters thus seem somewhat underwhelming. They would need to be buffed. At the same time you may think about moving a bit away from 5Es high-hp, low dmg monsters a bit.

I agree. Its intentional that all of the spells are more powerful because I've "squished" them.

Level Mass Effect 5e | Level 5th Edition
--- | ---
1st | 1st - 2nd
2nd | 3rd - 4th
3rd | 5th-6th
4th | 7th-8th
5th (though there are only spell slots, not spells) | 9th

Concerning weak monsters, this is a general complaint of 5th edition. I use the rules outlined in the Dungeon Master's Guide for creating monsters. There is a new set of rules in Volo's Guide to Monsters, but (from feedback I've read) it's mostly the same. 

All in all, weak monsters is something I do want to address at some point.

> The 6 classes are very different from each other, but there are still only 6 of them. Some subclasses are great, other feel similar. There simply isnt enough intra-class difference. Its a hard problem to solve though. Some ideas would be to de-couple feats and ability score advancement and give yout more feats.

First, have you read through my most [recent idea for classes](https://github.com/queryluke/masseffect-5e/issues/378)? I don't think it fixes the class differences problem, but I would be interested to hear your thoughts.

Which subclasses do you think are too similar?

>The Infiltrator has a shit ton of options to gain an advantage and sneak attacks. I like it, but it certainly is stronger than the Thief.

Agreed. The main problem is tactical cloak, which is always providing advantage. In my "major class changes?" post, the main idea is removing tech points. In turn, this would limit the number of times a player can cast tactical cloak. Current idea is proficiency bonus per long rest.

> The Sentinel is somewhat overlooaded. Why does it have Quick Cast and a Fighting Style when neither base classes are weapon-focussed and have it ? Stuff like that would better be moved to a Subclass.

The Sentinels are mean't to play like paladins. Fighting style is there to beef their weapon attacks and Quick Cast is a way to give them Extra Attack. However, I would still call sentinels a work in progress. I've been toying with the idea of making them more Bard-like (casting focused). But I'm not set on if that's the best choice.

> Soldier: Can you learn Combat Powers twice to get extra uses ? Overall they get very few combat powers, especially compared to the Infiltrator.

No. In the proposed changes, soldiers would get more opportunities than infiltrators. Also, I've been meaning to work on the Havok soldier. Some ideas for their subclass talents are to give them additional uses of their combat powers.

> Vanguard: The Nemisis subclass combined with dash and/or biotic punch somewhat bypasses the action and barrier economy, and I am not sure this is intendet.

That's a good point. I've made a note to look into this.


> Some upgrades are way to strong (Archon AI, or weak (Damage Reroll) for their price.

Agreed. The prices haven't really been audited. Some pieces, like gear, will continue to have these inconsistencies until other majors pieces (like classes and spells) seem fully formed.

> The weapon categories are somewhat uninspired. There is no real difference between some Heavy Pistols and Assault Rifles and Sniper Rifles. I think it would be good to have a unique weapon quality that only weapons of that cat have.

This is true for 5th edition as well. Weapon type is primarily a means to limit proficiency with weapons. Since there are fewer weapon types in ME5e, the problem may seem amplified. To combat this, weapons have certain qualities, but the qualities are limited to only that weapon. Heavy Pistols generally have double tap, but this doesn't mean other weapons cannot.

> Why do Shotguns of all weapons lack an AOE attack ? Another problems with them is is that they basically require Close Combat Shooter as a Fighting Style due to their low range.

An AoE is an interesting idea. The lack of one is simply to keep the system closer to 5th edition. A system like Savage worlds has really in-depth and fun rules for weapons, including damage drop-off and rate for fire. But I'm trying to keep this as close to 5th edition as possible. But an AoE for shotguns is an interesting idea to revisit.

Most shotguns have hip-fire, which negates the disadvantage.

> Burst Fire is only usefull if you have the Assault Fighting Style, due to the scaling of it. If you do have it seems very, very strong however.

Is the issue the DC of Burst fire? Overall, I think the burst fire mechanic is fine, it gives lower level characters without AoE an option for it. It's decent utility but it will never be as good as a spell. The fight style makes it really good as well, but the player will be limited by the number of consecutive times they can use it before they reload.

> I do have some Ideas about different weapon styles if it is wanted.

I'd be interested to hear about them. Could you post them in a new issue/thread? But, overall, my intent is not to create an entirely new game system. Whenever I create or edit rules, I'm always thinking of 2 things: Does this feel like Mass Effect? Does this align with 5th edition? I only want to break away from 5th edition when the goal is to add more Mass Effect style play. Having said that, I always appreciate new ideas. Additionally, I'm thinking about including a list of community rule variants on the website, allowing users to pick an choose really awesome ideas.

**Comment by BenutzernameIstBereitsVergeben** [comment]
I will write more this weekend, so only a short reply now. This probably includes some other Issues. 

>Which subclasses do you think are too similar?

Hard to say, its more a general feeling. Its not that the sublasses are per se bad, but considering that you hafe half the classes, subclasses should be *more* exciting and varied than in 5E. Yet there isnt really something like e.g. the storm path barbarian that really stand out.

> The main problem is tactical cloak

Tactical scan is just as problematic.

>The Sentinels are mean't to play like paladins. Fighting style is there to beef their weapon attacks and Quick Cast is a way to give them Extra Attack. However, I would still call sentinels a work in progress. I've been toying with the idea of making them more Bard-like (casting focused). But I'm not set on if that's the best choice.

I didnt really think of them as Paladins that much. It makes more sense then. But maybe put it into a subclass ? Casting focussed main class and then paladin-like subclass. 

>Is the issue the DC of Burst fire?

To be honest I may have misjudged the DC, 5Es sacings throws are just bad system imho. 

DC15 is easily beaten for some creatures relatively early, but others for others it will still be very easy to hit, even if hitting AC would be hard. 

>The lack of one is simply to keep the system closer to 5th edition.
>I only want to break away from 5th edition when the goal is to add more Mass Effect style play.
>But, overall, my intent is not to create an entirely new game system. 

The problem is that DnD isnt really made with the assumption that a) most people will be fighting with ranged weapons and b) that there only 6 classes. 

I see why one would want to keep close to 5E, but imho DnD just isnt made for a 6-class sci-fi RPG unless you start tweaking it a bit more in a bit more places.
