### ISSUE TITLE
New Feats

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#48]
Some possible new Feats:

Enhanced Optics- Your optic nerves have been enhanced by science to perceive more, and better. Gain low-light vision. If you already have low-light vision, gain darkvision. You now gain proficiency in Perception, Investigation, and Insight. If you are already proficient in any of these, gain a permanent +2 to the proficient skill(s). 

Big Game Hunter- The bigger they are, the harder you take them down. +1 to STR, and on non-sentient, organic creatures any size larger than yourself, gain a permanent +2 to damage rolls against them. 

Paint By Number- You're an artist, and a targeting laser is your paintbrush. When using a Heavy Weapon that requires a round to Target, you may target and fire on the same turn. 

Wealth of Knowledge- Your grasp of random factoids knows no bounds.+1 to INT, and you have advantage on the first Knowledge check you make after any long rest.

Featherlight- Travel light, travel fast. If you are carrying half or less of your maximum STR score, your walking speed increases by 10m. You also avoid triggering any pressure-activated traps or mines. 

A Beautiful Mine- You know how to sculpt explosives into works of art. You have advantage on disarming land-mines that you find, and enemies who trigger your mines make their DEX save at disadvantage. You can also choose certain squares of the mine's radius to exempt from damage.

Neat Trick- Evasive maneuvers take on new life when you're behind the helm. When another vehicle makes an area attack against a vehicle you're piloting, you take no damage on a successful Piloting check, and half damage on a failed one. You also gain proficiency in Piloting if you didn't have it already. 

Falling With Style- You turn crash landing a ship into a work of art. If your vehicle is shot down, you have advantage on all piloting checks to land it safely. You also gain proficiency in Piloting if you didn't have it already. 

Squad Leader (requires 15 CHA)- You know just what to say in a tight situation. As a bonus action, you can inspire all allies within earshot to instantly roll a shield die and regain that much in shields. They also lose any negative conditions that are affecting them as of this turn (freezing, poison, etc.). You may use this ability once per short rest.

Optimal Physiology- You and your MediGel have great chemistry. When using a charge of MediGel, maximize your hit die and restore that much HP. +1 to CON. 

More to come later.

**Comment by queryluke** [comment]
**Paint by Number** seems a little OP. Engineers only got a slight Targeting improvement at level 14. However, I liked the concept and mechanic so much I swapped the Engineer class feature for this one. 

Adjusting **Wealth of Knowledge** a bit to make it. Advantage will be for any INT based skill check, and increased occurrence to a short rest.

I wonder if **Neat Trick** and **Falling with Style** are better suited for a background, as they have limited combat potential. Of course, as there is plenty of potential in this system for vehicular battles.

**Squad leader** seems like a faster Inspiring Leader, but made me realize 2 things:
1. I don't have a lot of condition removal in this system (made a note to work on that for future spells)
2. I'm not a fan of inspiring leader, mainly because shield points already take the place of temporary hit points and it takes 30 min to cast.

So I switched shield die to hit die because I wanted to keep in line with the idea of inspiration->second wind. Gaining shields seems more...technical?...mechanical? Then, I spelled out the negative condition list, excluding a few conditions: blinded, deafened, invisible, lifted, and unconscious. Pretty much anything that it seemed the PC wouldn't have "control" over. I really like that there is now a talent that rewards high CHA.

**Optimal Physiology** is a slightly more beefed version of Durable. So we could change the name, but I am going to leave Durable for now.
