### ISSUE TITLE
Vanguard shotguns?

### ISSUE THREAD

**Issue by chikiko** [queryluke/masseffect-5e#58]
i love your work so far, but i find it so extremely odd that there there is no link to shotgun usage by vanguards.  shotgun usage was one of the most fundametal ways to play a vanguard even from the first mass effect, but for some reason there are fighting styles for pistol and smg play as well as a melee focused subclass.  melee didn't even really become a thing until me 3, but shotguns were iconic with vanguards since me 1.   it wouldn't seem off the wall to have a shotgun centric subclass but if nothing else there should at the very least be a shotgun centric fighting style for the vanguard.  in any case great job with this this, i can see myself playing/running this on a regular basis.

**Comment by queryluke** [comment]
Thanks for the feedback and compliments!

I agree completely. I originally had a fighting style called "sawed off," but removed it because I wanted the mechanic to apply to a weapon mod (weapon mods coming soon). 

But this left a void for shotgun wielders in general. I'll do some brainstorming on how to remedy this. Either a subclass, talent, or add a fighting style.

**Comment by chikiko** [comment]
there should probably be something for anyone who wants to use shotguns and something vanguard specific since it they have always had specific skills toward it.
