### ISSUE TITLE
Ship types and gameplay

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#59]
This is gonna be very dependent on how much space gameplay/combat you want to mix in, but for me personally, upgrading my ship in Mass Effect 2 was a great joy. I got a sense of satisfaction from knowing that whatever came my way, I could handle it if I upgraded my ship appropriately. I'm introducing my players to their ship, the SSV Joyeuse, an Alamo class frigate that will serve as their home base, transport, and central hub. Modeled loosely after the Normandy in its 5 deck structure, the Joyeuse sacrifices stealth for speed, recycling excess heat into battery cells that propel them even faster through mass relays. This lets the players get to most destinations within a day, even if they're across the galaxy. (with limits of course.)

I'm letting my players have a budget of credits that they get to spend on equipment, weapons, armor, upgrades for the ship, and staffing more crew. The ship has an AI, and a skeleton crew when the party boards. Just enough to get by. But, to make their operations smoother, they can hire better and extra crew, like shuttle/ground vehicle pilots, scientists, medics, quartermasters, cooks, engineers, etc. The better the crew and upgrades, the better your ship does in random encounters. I'm developing a table for pirates, asteroids, distress signals, resource caches, even a small chance to run into a damaged Reaper, left over from the war. You wanna be prepared for anything. The better your engineers, the less time you have to spend fixing broken parts. The better the pilot, the less damage you'll suffer in a dogfight. And the better the cook, the more temporary HP your crew may have when going into battle. You never know!

Let m,e know if this seems like a fun idea, and I'll share whatever I develop.

**Comment by queryluke** [comment]
Personally, when I hear "ships" or "vehicles", I get wary because that means lots of stats, additional feats/skills, space combat rules, etc. I've got other things I want to work on like the bestiary and I'm starting to sketch out the possibility of a character creator.

But if you're coming up with all this info, I say go for it! Seems like it will help expand the world and the ruleset. I'd rather give people options, so if some GMs/players want to mess around with space combat and ship upgrades, more power to them!

**Comment by queryluke** [comment]
duplicate of #159
