### ISSUE TITLE
Spell/Tech/Ability Questions

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#75]
I could not find the following information in the current ruleset:

- How to calculate Spell Attack Mod and Spell DC: I would assume that this is Wisdom for Biotics and Intelligence for Tech. Not sure about Combat abilities (or if it even applies)
- How to determine number of spell slots for Biotic characters. The rules indicate that, for example, a 1st level vanguard can learn or advance 3 level 1 spells or cantrips (plus barrier) but I'm not sure how many spell slots that character actually has.

**Comment by queryluke** [comment]
## Attack mods & DC
Yeah, originally, I had each class have it's own unique way to calculate spell save dc. But it makes more sense to keep these standard, because I can't really make a justification for Charisma being a spell casting mod for biotic abilities.

So, yeah:
Biotic Modifier = Wisdom
Tech Modifier = Int

This will give sentinels 2 dc's and attack modifiers to deal with, but that's really the only way to keep everything in line.

Each combat power should explicitly state how to calc the DC.

## Spell slots
The number of slots is listed on the progression table (far right)

**Comment by Swampson** [comment]
I think you could justify that Sentinels use Int for both their biotics & tech powers, _unless_ that would be OP because it would mean Sentinels really only need to have high Int and Wis becomes a dump stat for them?

**Comment by queryluke** [comment]
I think the allure of sentinels is the ability to mix and matcch a lot of different options. You can go melee, defense, biotic heavy, tech heavy, etc. So I think keeping it separate is best.

**Comment by Swampson** [comment]
I have made a notation in the Spellcasting rules as follows:
> By default, your character's Spell Save DC is calculated as normal: 8 + proficiency bonus + spellcasting ability modifier. Some individual abilities may have a Save DC that is calculated differently. In these cases, the Save DC is indicated in the spell/ability description.

I have added this because it doesn't look like every single power that calls for a saving throw lists the calculation for the DC, and it seemed prudent to explicitly state the standard DC calculation in the main rules.
I have also added a notation to the Sentinel class description (in the GSheet) that they use both Int and Wis and therefor have separate skills, attack mods, and save DCs for tech powers and biotic spells.
