### ISSUE TITLE
Vanguard Biotic Punch Ability

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#81]
Is the Biotic Punch ability damage a flat 1d8, or 1d8 + STR Mod? I would assume the latter. Also, does this count as a Standard Action, and if so is it considered an Attack action? (i.e., would it proc the Melee Specialist ability "When you take the Attack action, you can use a bonus action to make another melee weapon attack"?)

**Comment by queryluke** [comment]
Yeah, let's add the +str mod to the damage. I think I left it off because you also get to dash AND get a barrier tick. But Vanguard should be melee anyway, so this will be pretty bread and butter for them.

And, yes, all omni-tool attacks are considered melee weapon attacks and an Attack action. So a vanguard with Melee Specialist could use this twice in a single turn.

**Comment by Swampson** [comment]
I have updated the wording on this, but I'm having trouble getting the phb-app running correctly on my localhost so I think it will be better if @queryluke runs the generate.rb script to update the json files.

**Comment by queryluke** [comment]
It could be that your /phb-app/node_modules got out of whack when you checked out v040. 

Try the following:

```
rm -rf phb-app/node_modules
cd phb-app
npm install
```

Then load up the project:
In one terminal, cd to the site root: `jekyll serve` or `bundle exec jekyll serve`
In a separate terminal, cd to phb-app, and `gulp serve`

This is really funky, but is due to the fact that I'm running a single page web-app (Vuejs) within a static site generated app (jekyll).
